force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Error #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <label>Record ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Request_Pay_Load__c.field-meta.xml
<CustomField>
    <fullName>Request_Pay_Load__c</fullName>
    <label>Request Pay Load</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ICRA_Desc_Signing__c/ICRA_Desc_Signing__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ICRA_Desc_Signing</label>
</CustomObject>

force-app/main/default/objects/ICRA_Desc_Signing__c/fields/Certificate_URL__c.field-meta.xml
<CustomField>
    <fullName>Certificate_URL__c</fullName>
    <label>Certificate URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ICRA_Desc_Signing__c/fields/DSCMasterValues__c.field-meta.xml
<CustomField>
    <fullName>DSCMasterValues__c</fullName>
    <label>DSCMasterValues</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Credit_Note_Type__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Type__c</fullName>
    <label>Credit Note Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Credit_Note.recordType-meta.xml
<RecordType>
    <fullName>Credit_Note</fullName>
    <active>true</active>
    <label>Credit Note</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Manual_Invoice__c/Manual_Invoice__c.object-meta.xml
<CustomObject>
    <label>Manual Invoice</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Manual Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>OP Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR and IRN - Generated</fullName>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate OP Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Initiate OT Tax Invoice</fullName>
            </value>
            <value>
                <fullName>OT Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Initiate IB Tax Invoice</fullName>
            </value>
            <value>
                <fullName>IB Tax Invoice</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Porforma Invoice</fullName>
                <isActive>false</isActive>
                <label>Porforma Invoice</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/recordTypes/OPE.recordType-meta.xml
<RecordType>
    <fullName>OPE</fullName>
    <active>true</active>
    <label>OPE</label>
</RecordType>

force-app/main/default/objects/Manual_Invoice__c/recordTypes/Other_Services.recordType-meta.xml
<RecordType>
    <fullName>Other_Services</fullName>
    <active>true</active>
    <label>Other Services</label>
</RecordType>

force-app/main/default/classes/ICRA_dscSigning_MPRA_SoW.cls
public class ICRA_dscSigning_MPRA_SoW {
    public static string Auth(String InvId){
        HttpRequest req = new HttpRequest();
        string urlappend = '';
        ICRA_Desc_Signing__c [] dscInfo = [SELECT Id, End_Point__c, Client_Id__c, Client_Secret__c, Content_Type__c, Body__c, Name, DSCMasterValues__c, Certificate_URL__c FROM ICRA_Desc_Signing__c WHERE Name ='Authenticate' LIMIT 1];
        
        
        req.setEndpoint(dscInfo[0].End_Point__c);
        req.setMethod('POST');
        req.setHeader('clientid', dscInfo[0].Client_Id__c);
        req.setHeader('clientsecret', dscInfo[0].Client_Secret__c);
        req.setHeader('content-type', dscInfo[0].Content_Type__c);
        
        req.setTimeout(120000);
        
        string body = dscInfo[0].Body__c;
        req.setBody(body);
        Http http = new Http();
        HTTPResponse res = http.send(req);
        system.debug('status: '+res.getStatus());
        Map<String,Object> respMap = (Map<String,Object>) JSON.deserializeUntyped(res.getBody());
        Map<String,Object> respMap2 = (Map<String,Object>) respMap.get('AuthenticateResult');
        if(respMap2.get('Token') != null){
            return respMap2.get('Token').tostring();
        }else{
            string error = respMap2.get('ErrorMessage').tostring();
            Error_Log__c el = new Error_Log__c();
            el.Record_ID__c =InvId;
            el.Error_Message__c = error;
            el.Response__c = res.getBody();
            el.Request_Pay_Load__c = req.getBody();
            insert el;
            return null;
        }
        
    }
    
    public static Map<String,Object> SignedDoc(string InvId, String base64){ 
        String Token ='';
        // String objectType='';
        // ObjectType= ICRA_dscSigning.identifyObjectType(InvId);
        // List<Invoice__c> invoiceList = new List<Invoice__c>();
        // List<Manual_Invoice__c> manualInvoiceList = new List<Manual_Invoice__c>();
        if(!test.isRunningTest())
            Token = Auth(InvId);
        system.debug('Token='+Token);
        //Id invoiceTypeId = Schema.SObjectType.Invoice__c.getRecordTypeInfosByName().get('Invoice').getRecordTypeId();
        // if(objectType=='Invoice__c'){
        //     invoiceList= [select id, Invoice_Status__c, RecordTypeId, RecordType.DeveloperName, Credit_Note_Type__c from Invoice__c where id=:InvId];
        // }else if(objectType=='Manual_Invoice__c'){
        //     manualInvoiceList= [select id, Invoice_Status__c, RecordTypeId, RecordType.DeveloperName from Manual_Invoice__c where id=:InvId];
        // }
        ICRA_Desc_Signing__c [] dscInfo = [SELECT Id, End_Point__c, Client_Id__c, Client_Secret__c, Content_Type__c, Body__c, Name, DSCMasterValues__c, Certificate_URL__c FROM ICRA_Desc_Signing__c WHERE Name ='Authenticate' LIMIT 1];
        
        string status ='';
        if(string.isNotBlank(Token) || test.isRunningTest()){
            try{
                //ContentDocumentLink[] cdl = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: InvId AND (NOT ContentDocument.LatestPublishedVersion.Title Like'%Signed%') ORDER BY SystemModstamp DESC LIMIT 1];
                if(!string.isBlank(base64)){
                    //ContentVersion[] cv = [SELECT VersionData,Title FROM ContentVersion WHERE ContentDocumentId = :cdl[0].ContentDocumentId];
                    //string paramvalue = EncodingUtil.base64Encode(cv[0].VersionData);
                    
                    HttpRequest req = new HttpRequest();
                    req.setEndpoint(dscInfo[0].Certificate_URL__c);
                    req.setMethod('POST');
                    req.setHeader('token', Token);
                    
                    //req.setTimeout(120000);
                    string body = '{"getDSCSignedBytesForPDFParams":{"originalPdfBytes":"'+base64+'","DSCMasterValues":["'+System.Label.Signing_Authority_MPRA_SoW/*dscInfo[0].DSCMasterValues__c*/+'"],"digitalCertificatePerSegmentForPdfList":[{"CertificateValidTo":""}],"passwordGSTIN":"","CurrFileName":"Test","irn":"","QRCode":""}}';            
                    req.setHeader('content-type', 'application/json');
                    req.setBody(body);
                    req.setTimeout(120000);
                    Http http = new Http();
                    HTTPResponse res = http.send(req);
                    system.debug('status: '+res.getStatus());
                    system.debug('response: '+req);
                    system.debug('Body: '+body);
                    Map<String,Object> respMap = (Map<String,Object>) JSON.deserializeUntyped(res.getBody());
                    Map<String,Object> respMap2 = (Map<String,Object>) respMap.get('GetDSCSignedBytesForPDFResult');
                    String returnFile;
                    return respMap2;
                    /*if(respMap2.get('SignedFile') != null){
                        system.debug('Response======>>>>'+respMap2.get('SignedFile').tostring());
                        returnFile = respMap2.get('SignedFile').tostring();
                        returnFile= returnFile.removeEnd('"');
                        returnFile= returnFile.removeStart('"');
                        
                        Blob myBlob = EncodingUtil.base64Decode(returnFile);
                        ContentVersion ContentInsert = new ContentVersion();
                        ContentInsert.Title = 'Doc'+' | Signed';
                        ContentInsert.VersionData = myBlob;
                        ContentInsert.PathOnClient = '/'+' | Signed.pdf';
                        insert ContentInsert;
                        ContentVersion[] insertedContent = [select id, ContentDocumentId from ContentVersion WHERE Id =: ContentInsert.Id];
                        system.debug('ContentInsert.ContentDocumentId>> '+insertedContent[0].ContentDocumentId);
                        ContentDocumentLink cl = new ContentDocumentLink();
                        cl.ContentDocumentId = insertedContent[0].ContentDocumentId;
                        cl.LinkedEntityId = InvId; //Shared with record ID
                        cl.ShareType = 'V';
                        cl.Visibility = 'AllUsers';
                        insert cl;
                        // if(objectType=='Invoice__c'){    
                        //     if(invoiceList.size()>0 && invoiceList[0].RecordType.DeveloperName=='Invoice'){
                        //         invoiceList[0].Invoice_Status__c='Tax Invoice';
                        //         update invoiceList;
                        //     }else if(invoiceList.size()>0 && invoiceList[0].RecordType.DeveloperName=='Credit_Note' && invoiceList[0].Credit_Note_Type__c=='GST Credit Note'){
                        //         invoiceList[0].Invoice_Status__c='GST Credit Note';
                        //         update invoiceList;
                        //     } 
                        // }else if(objectType=='Manual_Invoice__c'){
                        //     if(manualInvoiceList.size()>0 && manualInvoiceList[0].RecordType.DeveloperName=='OPE'){
                        //         manualInvoiceList[0].Invoice_Status__c='OP Tax Invoice';
                        //         update manualInvoiceList;
                        //     }else if(manualInvoiceList.size()>0 && manualInvoiceList[0].RecordType.DeveloperName=='Other_Services'){
                        //         manualInvoiceList[0].Invoice_Status__c='OT Tax Invoice';
                        //         update manualInvoiceList;
                        //     }
                         //}    
                        status = 'success';
                    }else{
                        string error = respMap2.get('ErrorMessage').tostring();
                        Error_Log__c el = new Error_Log__c();
                        el.Record_ID__c =InvId;
                        el.Error_Message__c = error;
                        el.Response__c = res.getBody();
                        insert el;
                        status = error+' , Please check error log';
                    }*/
                }else{
                    //status= 'No Document found';
                    return null;
                }
            }catch(exception e){
                system.debug('line: '+e.getLineNumber());
                system.debug('err: '+e.getMessage());
                return null;
                //throw new AuraHandledException('Error Occured: '+e.getMessage());
            }
        }else{
            //status = 'Could not authenticate, Please check error log';
            return null;
        }
        //return status ;
    }

    // public Static String identifyObjectType(Id recordId) {
    //     SObject record = recordId.getSObjectType().newSObject(recordId);
    //     String objectType = String.valueOf(record.getSObjectType());
    //     return objectType;
    // }
}