force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verification Pending</fullName>
                <default>true</default>
                <label>Verification Pending</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Batch_Process__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process__c</fullName>
    <label>Batch Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICRA_Generate_Proforma_Invoice_Batch</fullName>
            </value>
            <value>
                <fullName>ICRA_Generate_Tax_Invoice_Batch</fullName>
            </value>
            <value>
                <fullName>ICRA_CreateRollover_T_Logic</fullName>
            </value>
            <value>
                <fullName>ICRA_CreateRollover_T_Logic_Manual</fullName>
            </value>
            <value>
                <fullName>ICRA_Invoice_Status_Update_Batch</fullName>
            </value>
            <value>
                <fullName>ICRA CreateRollover T Logic</fullName>
                <isActive>false</isActive>
                <label>ICRA CreateRollover T Logic</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Transaction Logs</relationshipLabel>
    <relationshipName>Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <description>to store the type of operation</description>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transaction Logs</relationshipLabel>
    <relationshipName>Transaction_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ICRA_TransactionLogHandler.cls
public with sharing class ICRA_TransactionLogHandler{

    private static List<Transaction_Log__c> logs = new List<Transaction_Log__c>();

    public static void addLog(String batchName, Id oppId, Id invoiceId, String operation, String message) {
        Transaction_Log__c errorLog = new Transaction_Log__c();
        errorLog.Batch_Process__c = batchName;
        errorLog.Opportunity__c = oppId;
        errorLog.Invoice__c = invoiceId;
        errorLog.Operation__c = operation;
        errorLog.Error_Message__c = message;
        errorLog.Status__c = 'Failed';
        logs.add(errorLog);
    }

    public static void saveLogs(){
        if (!logs.isEmpty()) {
            insert logs;
            logs.clear(); 
        }
    }
}