force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice No</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credit Note</relationshipLabel>
    <relationshipName>Credit_Note</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/isFirst_InvoiceLine_Item__c.field-meta.xml
<CustomField>
    <fullName>isFirst_InvoiceLine_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isFirst_InvoiceLine_Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <formula>Invoice_No__r.Check_Current_Year__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Financial Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Invoice_No__c</fullName>
    <label>Invoice No</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <formula>TEXT( Invoice_No__r.Invoice_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice  Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/isFirst_InvoiceLine_Item__c.field-meta.xml
<CustomField>
    <fullName>isFirst_InvoiceLine_Item__c</fullName>
    <formula>Invoice_No__r.isFirst_InvoiceLine_Item__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isFirst InvoiceLine Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Amount_for_invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_for_invoice_Amount__c</fullName>
    <formula>/*Invoice_Taxable_Amount__c +(CEILING(Invoice_Taxable_Amount__c) *  GST_Rate__c )*/
 Total_Invoice_Amount_WF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Invoice Amount O</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Total_Invoice_Amount_WF__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount_WF__c</fullName>
    <label>Total Invoice Amount WF</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ICRA_InvoiceLineRollUpHandler.cls
/**
* @description       : 
* @author            : ChangeMeIn@UserSettingsUnder.SFDoc
* @group             : 
* @last modified on  : 03-22-2021
* @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
* Modifications Log 
* Ver   Date         Author                               Modification
* 1.0   03-22-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class ICRA_InvoiceLineRollUpHandler { 
    public static boolean firstRun = true; 
    
    public void rollUpInvoiceLines(List<Invoice_Line_Item__c> invoiceLineList){
        
        Set<Id> opportunityIdSet = new Set<Id>();
        Map<Id,RollUpSum> lineSum = new Map<Id,RollUpSum>();
        
        for(Invoice_Line_Item__c lineRecord : invoiceLineList){
            
            opportunityIdSet.add(lineRecord.Opportunity_Name__c);
        } 
        
        Invoice_Line_Item__c [] tempLineList  =  [
            SELECT Id, Opportunity_Name__c, Total_Amount_for_invoice_Amount__c, Invoice_Status__c, Financial_Year__c, Total_Invoice_Amount_WF__c, Invoice_No__c,
            	Invoice_No__r.isFirst_InvoiceLine_Item__c, Invoice_No__r.Opportunity_Name__c
            FROM Invoice_Line_Item__c 
            WHERE Opportunity_Name__c IN:opportunityIdSet           
            LIMIT 50000]; 
        
        if(tempLineList.Size() >0){ 
            
            lineSum = rollUptoOpportunity(tempLineList);
        }
        
        List<Opportunity> opportunityList = new List <Opportunity>();  
        
        if(lineSum.keySet() != null){
            
            for(Opportunity opportunityRecord : [
                SELECT Id, Name, Annual_Surveillance_Opp_Amount__c, Annual_Initial_Rating_Amount_1__c, Total_Invoice_Amount_1__c
                FROM Opportunity 
                WHERE Id In: lineSum.keySet()
                LIMIT 50000]){   
                    
                    if(lineSum.containsKey(opportunityRecord.Id)){  
                        Opportunity tempRecord = new Opportunity(); 
                        tempRecord.Id = opportunityRecord.Id;
                        tempRecord.Annual_Surveillance_Opp_Amount__c = lineSum.get(opportunityRecord.Id).annualSurveillance;
                        tempRecord.Annual_Initial_Rating_Amount_1__c = lineSum.get(opportunityRecord.Id).annualInitialRating;
                        tempRecord.Total_Invoice_Amount_1__c = lineSum.get(opportunityRecord.Id).invoiceAmount;
                        opportunityList.add(tempRecord);
                    } 
                }
        }  
        
        if(opportunityList.size()>0){
            
            Update opportunityList;
        }  
    }  
    public Map<Id,RollUpSum> rollUptoOpportunity(List<Invoice_Line_Item__c> invoiceLineList){  
        Map<Id,RollUpSum> rollUpSumMap = new Map<Id,RollUpSum>();
        
        for(Invoice_Line_Item__c lineRecord : invoiceLineList){ 
         
            if(lineRecord.Opportunity_Name__c != null){ 
                
                if(rollUpSumMap.containsKey(lineRecord.Opportunity_Name__c)){
                    
                    RollUpSum tempSum = rollUpSumMap.get(lineRecord.Opportunity_Name__c); 
                    
                    if(lineRecord.Invoice_Status__c == Label.Invoice_Rollup_Filter){ 
                        
                        if(tempSum.invoiceAmount > 0){
                            tempSum.invoiceAmount -= lineRecord.Total_Amount_for_invoice_Amount__c;
                            
                            if(lineRecord.Financial_Year__c == 'Current Year' &&  tempSum.annualSurveillance >0  ){ 
                                
                                tempSum.annualSurveillance -= lineRecord.Total_Amount_for_invoice_Amount__c; 
                            }
                            if(lineRecord.Financial_Year__c == 'Current Year' &&  tempSum.annualInitialRating >0  ){ 
                                
                                tempSum.annualSurveillance -= lineRecord.Total_Amount_for_invoice_Amount__c; 
                            }
                        }
                        
                    }else{
                        
                        tempSum.invoiceAmount += lineRecord.Total_Amount_for_invoice_Amount__c;
                        
                        if(lineRecord.Financial_Year__c == 'Current Year'){
                            
                            tempSum.annualSurveillance += lineRecord.Total_Amount_for_invoice_Amount__c;
                            tempSum.annualInitialRating += lineRecord.Total_Amount_for_invoice_Amount__c; 
                        } 
                    } 
                    rollUpSumMap.put(lineRecord.Opportunity_Name__c,tempSum); 
                    
                }else{
                    
                    RollUpSum sum = new RollUpSum(); 
                    if(lineRecord.Invoice_Status__c == Label.Invoice_Rollup_Filter){
                        sum.invoiceAmount = 0.0; 
                        if(lineRecord.Financial_Year__c == 'Current Year'){ 
                            sum.annualSurveillance = 0.0;
                            sum.annualInitialRating = 0.0;
                        } 
                    }else{
                        
                        sum.invoiceAmount = lineRecord.Total_Amount_for_invoice_Amount__c;
                        if(lineRecord.Financial_Year__c == 'Current Year'){
                            
                            sum.annualSurveillance = lineRecord.Total_Amount_for_invoice_Amount__c;
                            sum.annualInitialRating = lineRecord.Total_Amount_for_invoice_Amount__c;
                        } 
                    } 
                    rollUpSumMap.put(lineRecord.Opportunity_Name__c,sum); 
                }  
            } 
        }  
        return rollUpSumMap; 
    }  
    
    public class RollUpSum{
        
        public Double invoiceAmount = 0;
        public Double annualSurveillance = 0;
        public Double annualInitialRating  = 0; 
        
        public RollUpSum(){} 
    } 
}