force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proforma_Invoice_ok__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice_ok__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true email will be send to customer with attached PI invoice pdf</description>
    <label>Proforma Invoice ok</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_PI_OK_InvoiceDate.cls
public class ICRA_PI_OK_InvoiceDate {
    @invocableMethod
    public static void ICRA_PI_OK_InvoiceDate( List<Opportunity> oppList1){
        List<Invoice__c> invoiceList = new List<Invoice__c>();
        List<Invoice__c> updateInvoiceRecord = new List<Invoice__c>();
        Set<Id> oppIdSet = new Set<Id>();
        
        for(Opportunity oppRecord : oppList1){
            oppIdSet.add(oppRecord.Id);
            
        }
        if(oppIdSet.size() > 0){
            for(Invoice__c invoiceRecord : [SELECT Id,Name,Opportunity_Name__r.Id,Invoice_Created_Date__c,Invoice_Status__c,Opportunity_Name__r.Proforma_Invoice_ok__c 
                                            FROM Invoice__c 
                                            WHERE recordType.Name = 'Invoice' AND
                                            Opportunity_Name__r.Id IN: oppIdSet AND
                                            Opportunity_Name__r.Proforma_Invoice_ok__c = true AND
                                            Invoice_Status__c = 'Proforma Invoice'
                                            LIMIT 1]){
                                                invoiceRecord.Invoice_Created_Date__c = System.today();
                                                updateInvoiceRecord.add(invoiceRecord);
                                            }
        }
        update updateInvoiceRecord;
    }    
}