force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_PI_OK_InvoiceDate_Test.cls
@isTest
public class ICRA_PI_OK_InvoiceDate_Test {
    @isTest
    public static void PI_OK_InvoiceDate(){
        List<Opportunity> oppList = new List<Opportunity>();
        Account accountRecord =  ICRA_TestDataFactory.CreateAccount('Name', 'Issuer', null); 
        
        Contact contactRecord = ICRA_TestDataFactory.createContact('name', 'Yes', 'Account Contact', accountRecord.Id);
        
        Opportunity opportunityRecord = ICRA_TestDataFactory.creatOpportunity('name', 'Surveillance', accountRecord.Id);   
        insert opportunityRecord;
        
        Opportunity opportunityRecord2 = ICRA_TestDataFactory.creatOpportunity('name', 'Surveillance', accountRecord.Id);   
        insert opportunityRecord2;
        
        oppList.add(opportunityRecord);
        oppList.add(opportunityRecord2);
        
        Invoice__c invoiceRecord  = ICRA_TestDataFactory.createInvoice('Invoice',opportunityRecord.Id, null,'Proforma Invoice'); 
        invoiceRecord.Invoice_Created_Date__c = system.today();
        insert invoiceRecord;
        
        Test.startTest();
        ICRA_PI_OK_InvoiceDate.ICRA_PI_OK_InvoiceDate(oppList);
        Test.stopTest();
    }

}