force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <formula>IF(
AND(
ISPICKVAL(Opportunity_Name__r.Already_Invoiced__c,&apos;Yes&apos;),
Opportunity_Name__r.RecordType.Name ==&apos;Surveillance&apos;),
Opportunity_Name__r.Past_Invoice_Number__c ,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)
),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Initiate Tax Invoice&apos;),
Auto_Generated_Tax_Invoice__c,
NOT(ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;))),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
NOT(ISBLANK(TEXT(Invoice_Status__c))),
NOT(ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)),
OR(
AND(Auto_Generated_Tax_Invoice__c,
ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;)), 
!Auto_Generated_Tax_Invoice__c
)
),Service_Code__c+&apos;/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c +&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),&apos;&apos;))
))</formula>
    <label>Bill No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Dsc_Sign__c.field-meta.xml
<CustomField>
    <fullName>Dsc_Sign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dsc Sign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Used in Credit note PDF and Reports (Convert date to Text)</description>
    <formula>Invoice_No__r.Invoice_Created_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date CN</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PI_Send__c.field-meta.xml
<CustomField>
    <fullName>PI_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PI Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_DSC_Sign__c.field-meta.xml
<CustomField>
    <fullName>Tax_DSC_Sign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax DSC Sign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax_Send__c.field-meta.xml
<CustomField>
    <fullName>Tax_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_EamilViewController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-13-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class ICRA_EamilViewController {
    public List<InvoiceData> invoiceDataList {get;set;} 
    Map<Id,List<String>> optyEmailRecipsMap {get;set;}
    public String invoiceStatus {set;get;}
    public EmailTemplate[] piEmailTemplate;
    public EmailTemplate [] taxEmailTemplate;
    public OrgWideEmailAddress [] owea; 

    public ICRA_EamilViewController(){
        invoiceDataList = new List<InvoiceData>(); 
        optyEmailRecipsMap = new Map<Id,List<String>>();
        
        piEmailTemplate = [SELECT DeveloperName, Id, Subject, Description, HtmlValue, Body FROM EmailTemplate WHERE DeveloperName = 'End_User_Proforma_Invoice_Notification' LIMIT 1];
        taxEmailTemplate = [SELECT DeveloperName, Id, Subject, Description, HtmlValue, Body FROM EmailTemplate WHERE DeveloperName = 'End_User_Invoice_Notification' LIMIT 1];
        owea = [SELECT Id FROM OrgWideEmailAddress where Address = 'billing@icraindia.info'];

        invoiceStatus = 'today';
        fetchInvoiceList(); 
    }
    
    public void fetchInvoiceList(){
        invoiceDataList.clear();
        optyEmailRecipsMap.clear();
        String filter =  invoiceStatus; 
        System.debug('====== filter ===='+filter);
        Map<Id, Invoice__c> invoiceRecordMap = new Map<Id, Invoice__c>();
        List<InvoiceData> tempInvoiceDataList = new List<InvoiceData>(); 
        // Invoice Record and PDF Files 
        Map<Id, ContentDocumentLink> pdfInvoiceMap = new Map<Id, ContentDocumentLink>();

        // Email notification.
        Set<Messaging.SingleEmailMessage> emailSet = new set<Messaging.SingleEmailMessage>(); 
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        List<String> ccAddress = new List<String>(); 


        if(filter == 'PI'){
            System.debug('======== Data Filter ======'+filter);
            invoiceRecordMap = new Map<Id, Invoice__c> ([
                SELECT Id, Name,RecordType.Name,Dsc_Sign__c,Bill_No__c,Invoice_Date__c,Error_Message__c,Invoice_Status__c,Invoice_Created_Date__c,Opportunity_Name__c,Opportunity_Name__r.Billing_Start_Date__c, Tax_Send__c, PI_Send__c, Tax_DSC_Sign__c, Opportunity_Name__r.Owner.Name, Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Owner.Manager.Email,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email 
                FROM Invoice__c  WHERE Contact_Name__r.Email != null AND RecordType.Name = 'Invoice' AND Invoice_Status__c = 'Proforma Invoice' AND PI_Send__c = false
            ]);

        } else if(filter == 'Tax'){
            System.debug('======== Data Filter ======'+filter);
            invoiceRecordMap = new Map<Id, Invoice__c> ([
                SELECT Id, Name,RecordType.Name,Dsc_Sign__c,Bill_No__c,Invoice_Status__c,Error_Message__c,Invoice_Date__c,Invoice_Created_Date__c,Opportunity_Name__c,Opportunity_Name__r.Billing_Start_Date__c, Tax_Send__c, PI_Send__c, Tax_DSC_Sign__c,  Opportunity_Name__r.Owner.Name, Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Owner.Manager.Email,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email 
                FROM Invoice__c  WHERE Contact_Name__r.Email != null AND RecordType.Name = 'Invoice' AND Invoice_Status__c != 'Proforma Invoice' AND Invoice_Status__c != 'Canceled'
            ]);
        }else if(filter == 'PI Sent'){
            System.debug('======== Data Filter ======'+filter);
            invoiceRecordMap = new Map<Id, Invoice__c> ([
                SELECT Id, Name,RecordType.Name,Dsc_Sign__c,Bill_No__c,Invoice_Status__c,Error_Message__c,Invoice_Date__c,Invoice_Created_Date__c,Opportunity_Name__c,Opportunity_Name__r.Billing_Start_Date__c, Tax_Send__c, PI_Send__c, Tax_DSC_Sign__c,  Opportunity_Name__r.Owner.Name, Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Owner.Manager.Email,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email 
                FROM Invoice__c  WHERE Contact_Name__r.Email != null AND RecordType.Name = 'Invoice' AND Invoice_Status__c = 'Proforma Invoice' AND PI_Send__c = true
            ]);
        }else if(filter == 'Tax Sent'){
            System.debug('======== Data Filter ======'+filter);
            invoiceRecordMap = new Map<Id, Invoice__c> ([
                SELECT Id, Name,RecordType.Name,Dsc_Sign__c,Bill_No__c,Invoice_Status__c,Error_Message__c,Invoice_Date__c,Invoice_Created_Date__c,Opportunity_Name__c,Opportunity_Name__r.Billing_Start_Date__c, Tax_Send__c, PI_Send__c,Tax_DSC_Sign__c,  Opportunity_Name__r.Owner.Name, Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Owner.Manager.Email,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email 
                FROM Invoice__c  WHERE Contact_Name__r.Email != null AND RecordType.Name = 'Invoice' AND Invoice_Status__c != 'Proforma Invoice' AND Invoice_Status__c != 'Canceled' AND Tax_Send__c = true
            ]);
        }else if(filter == 'error'){
            System.debug('======== Data Filter ======'+filter);
            invoiceRecordMap = new Map<Id, Invoice__c> ([
                SELECT Id, Name,RecordType.Name,Dsc_Sign__c,Bill_No__c,Error_Message__c,Invoice_Status__c,Invoice_Date__c,Invoice_Created_Date__c,Opportunity_Name__c,Opportunity_Name__r.Billing_Start_Date__c, Tax_Send__c, PI_Send__c, Tax_DSC_Sign__c,  Opportunity_Name__r.Owner.Name, Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Owner.Manager.Email,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email 
                FROM Invoice__c  WHERE Contact_Name__r.Email != null AND RecordType.Name = 'Invoice' AND Invoice_Status__c = 'QR and IRN - Failed'
            ]);
        }else if(filter == 'today'){
            System.debug('======== Data Filter ======'+filter);
            invoiceRecordMap = new Map<Id, Invoice__c> ([
                SELECT Id, Name,RecordType.Name,Dsc_Sign__c,Error_Message__c,Bill_No__c,Invoice_Status__c,Invoice_Date__c,Invoice_Created_Date__c,Opportunity_Name__c,Opportunity_Name__r.Billing_Start_Date__c, Tax_Send__c, PI_Send__c,Tax_DSC_Sign__c,  Opportunity_Name__r.Owner.Name, Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Owner.Manager.Email,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email 
                FROM Invoice__c  WHERE Contact_Name__r.Email != null AND RecordType.Name = 'Invoice' AND   Invoice_Status__c != 'Canceled' AND Invoice_Date__c = TODAY
            ]);
        }

        System.debug('======= invoiceList ====== '+invoiceRecordMap); 

        if(invoiceRecordMap != null){
            System.debug('======= invoice Id List ====== '+invoiceRecordMap.keySet());
            System.debug('======= invoice  List ====== '+invoiceRecordMap.values());

            if(invoiceRecordMap.keySet().size() > 0){
                if(filter == 'PI'){ 
                   System.debug('====== invoiceRecordMap ====='+filter ); //-Signed
                    for(ContentDocumentLink pdffile : [ SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                            ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                            FROM ContentDocumentLink 
                            WHERE LinkedEntityId IN: invoiceRecordMap.keySet() AND 
                            ContentDocument.LatestPublishedVersion.ContentSize > 1023 AND
                            ContentDocument.LatestPublishedVersion.Title Like'%INV%'
                            ORDER BY 
                            SystemModstamp ASC
                    ]){
                                                    
                        pdfInvoiceMap.put(pdffile.LinkedEntityId, pdffile);
                                                    
                    }

                } else if(filter == 'Tax'){
                    System.debug('====== invoiceRecordMap ====='+filter );
                    for(ContentDocumentLink pdffile : [ SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                            ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                            FROM ContentDocumentLink 
                            WHERE LinkedEntityId IN: invoiceRecordMap.keySet() AND 
                            ContentDocument.LatestPublishedVersion.ContentSize > 1023 AND
                            (NOT(ContentDocument.LatestPublishedVersion.Title Like'%INV%'))
                            ORDER BY 
                            SystemModstamp ASC
                    ]){                                
                        pdfInvoiceMap.put(pdffile.LinkedEntityId, pdffile);
                                                        
                    }
                }else{
                    for(ContentDocumentLink pdffile : [ SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                            ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                            FROM ContentDocumentLink 
                            WHERE LinkedEntityId IN: invoiceRecordMap.keySet() AND 
                            ContentDocument.LatestPublishedVersion.ContentSize > 1023 
                            ORDER BY 
                            SystemModstamp ASC
                    ]){                                
                        pdfInvoiceMap.put(pdffile.LinkedEntityId, pdffile);
                                                        
                    }
                }

                System.debug('========= pdfInvoiceMap ====='+pdfInvoiceMap);

                if(pdfInvoiceMap != null){
                    
                    Set<Id> opportunityIds = new Set<Id>();
                    for(Invoice__c inv : invoiceRecordMap.Values()){
                        opportunityIds.add(inv.Opportunity_Name__c);
                    }
                    for(OpportunityContactRole ocr : [SELECT Id,Contact.Email,OpportunityId FROM OpportunityContactRole WHERE OpportunityId IN :opportunityIds AND Contact.Email!=null AND Role = 'Email Recipient']){
                        if(optyEmailRecipsMap.containsKey(ocr.OpportunityId)){
                            optyEmailRecipsMap.get(ocr.OpportunityId).add(ocr.Contact.Email);
                        }else{
                            optyEmailRecipsMap.put(ocr.OpportunityId,new List<String>{ocr.Contact.Email});
                        }
                    }
                    
                    if(filter == 'PI'){
                        for(ContentDocumentLink pdfFile : pdfInvoiceMap.values()){
                            ccAddress.clear();
                            InvoiceData invoiceDataRecord = new InvoiceData();
                            Messaging.SingleEmailMessage emailRecord = new Messaging.SingleEmailMessage();
                            if(invoiceRecordMap.containsKey(pdfFile.LinkedEntityId)){ 
                                invoiceDataRecord.selectRecord = false;
                                invoiceDataRecord.selectRecord = false;
                                invoiceDataRecord.invoiceRecord = invoiceRecordMap.get(pdfFile.LinkedEntityId); 
                                invoiceDataRecord.emailRecord = bindEmail(pdfFile, invoiceRecordMap.get(pdfFile.LinkedEntityId), 'Proforma ');
                                System.debug('======= PI  invoiceDataRecord'+invoiceDataRecord);
                                invoiceDataList.add(invoiceDataRecord);
                            }  
                        }

                    }else if(filter == 'Tax'){
                        for(ContentDocumentLink pdfFile : pdfInvoiceMap.values()){
                            ccAddress.clear();
                            InvoiceData invoiceDataRecord = new InvoiceData();
                            Messaging.SingleEmailMessage emailRecord = new Messaging.SingleEmailMessage();
                            if(invoiceRecordMap.containsKey(pdfFile.LinkedEntityId)){ 
                                invoiceDataRecord.selectRecord = false;
                                invoiceDataRecord.invoiceRecord = invoiceRecordMap.get(pdfFile.LinkedEntityId); 
                                invoiceDataRecord.emailRecord = bindEmail(pdfFile, invoiceRecordMap.get(pdfFile.LinkedEntityId), ''); 
                                System.debug('======= Tax invoiceDataRecord'+invoiceDataRecord);
                                invoiceDataList.add(invoiceDataRecord);
                            }  
                        }
                    }else{
                        for(ContentDocumentLink pdfFile : pdfInvoiceMap.values()){
                            ccAddress.clear();
                            InvoiceData invoiceDataRecord = new InvoiceData();
                            Messaging.SingleEmailMessage emailRecord = new Messaging.SingleEmailMessage();
                            if(invoiceRecordMap.containsKey(pdfFile.LinkedEntityId)){ 
                                invoiceDataRecord.selectRecord = false;
                                invoiceDataRecord.invoiceRecord = invoiceRecordMap.get(pdfFile.LinkedEntityId); 
                                invoiceDataRecord.emailRecord = bindEmail(pdfFile, invoiceRecordMap.get(pdfFile.LinkedEntityId), ''); 
                                System.debug('======= Tax invoiceDataRecord'+invoiceDataRecord);
                                invoiceDataList.add(invoiceDataRecord);
                            }  
                        }
                    } 
                    System.debug('======= tempInvoiceDataList === '+invoiceDataList);
                    System.debug('======= tempInvoiceDataList.size === '+invoiceDataList.size());
                }
            } 
        }
        

    }

    public void sendSelectedEmail(){
        
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        Map<Id, Invoice__c > invoiceMap = new Map<Id,Invoice__c>();
        List<Invoice__c> updateInvoiceList = new List<Invoice__c>();
        Map<Id, ContentDocumentLink> pdfInvoiceMap = new Map<Id, ContentDocumentLink>();
        System.debug('======== invoiceDataList ======'+ invoiceDataList.size());
        if(invoiceDataList.size() > 0){ //PI_Send__c
            for(InvoiceData invoiceEmail : invoiceDataList){
                if(invoiceEmail.selectRecord == true && invoiceEmail.invoiceRecord != null){ 
                    invoiceMap.put(invoiceEmail.invoiceRecord.Id, invoiceEmail.invoiceRecord); 
                }
            }

            if(invoiceStatus == 'PI'){
                for(ContentDocumentLink pdffile : [ SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                    ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                    FROM ContentDocumentLink 
                    WHERE LinkedEntityId IN: invoiceMap.keySet() AND 
                    ContentDocument.LatestPublishedVersion.ContentSize > 1023 AND
                    ContentDocument.LatestPublishedVersion.Title Like'%INV%'
                    ORDER BY SystemModstamp ASC
                ]){
                                                
                    pdfInvoiceMap.put(pdffile.LinkedEntityId, pdffile);
                                                
                }
                
            }else if(invoiceStatus == 'Tax'){
                for(ContentDocumentLink pdffile : [ SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                    ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                    FROM ContentDocumentLink 
                    WHERE LinkedEntityId IN: invoiceMap.keySet() AND 
                    ContentDocument.LatestPublishedVersion.ContentSize > 1023 AND
                    (NOT(ContentDocument.LatestPublishedVersion.Title Like'%INV%'))
                    ORDER BY SystemModstamp ASC
                ]){
                                                
                    pdfInvoiceMap.put(pdffile.LinkedEntityId, pdffile);
                                                
                }
                
            }else{
                for(ContentDocumentLink pdffile : [ SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                    ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                    FROM ContentDocumentLink 
                    WHERE LinkedEntityId IN: invoiceMap.keySet() AND 
                    ContentDocument.LatestPublishedVersion.ContentSize > 1023 
                    ORDER BY SystemModstamp ASC
                ]){                            
                    pdfInvoiceMap.put(pdffile.LinkedEntityId, pdffile);
                                                
                } 
            }
            

            System.debug('======== pdfInvoiceMap ======'+ pdfInvoiceMap);
            if(pdfInvoiceMap != null){
                for(ContentDocumentLink pdfFile : pdfInvoiceMap.values()){

                    if(invoiceMap.get(pdfFile.LinkedEntityId).Invoice_Status__c == 'Proforma Invoice'){
                        emailList.add(bindEmail(pdfFile, invoiceMap.get(pdfFile.LinkedEntityId), 'Proforma ')); 
                        invoiceStatus = 'PI';
                        Invoice__c invoice = new Invoice__c();
                        invoice.Id = pdfFile.LinkedEntityId;
                        invoice.PI_Send__c = true;
                        updateInvoiceList.add(invoice);
                    }else{
                        emailList.add(bindEmail(pdfFile, invoiceMap.get(pdfFile.LinkedEntityId), '')); 
                        invoiceStatus = 'Tax';
                        Invoice__c invoice = new Invoice__c();
                        invoice.Id = pdfFile.LinkedEntityId;
                        invoice.Tax_Send__c = true;
                        updateInvoiceList.add(invoice);
                    } 
                }
            } 

            System.debug('======== emailList ======'+ emailList.size());
            if(emailList.size() > 0){
                try{ 
                    if(updateInvoiceList.size() > 0 ){
                        Messaging.sendEmail(emailList);
                        Update updateInvoiceList;
                        
                    }
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, emailList.size() +' Email Sent to the customer'));
					fetchInvoiceList();
                }catch(Exception e){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Try after sometime.'));
                } 
            }
            
        } 
    }

    public Messaging.SingleEmailMessage bindEmail(ContentDocumentLink pdfFile, Invoice__c invoiceRecord, String invoiceType ){
        List<String> ccAddress = new List<String>();
        Messaging.SingleEmailMessage emailRecord = new Messaging.SingleEmailMessage();
        if(invoiceRecord != null && pdfFile != null ){ 
            ccAddress.clear();
            emailRecord.setTargetObjectId(invoiceRecord.Contact_Name__c);
            emailRecord.setTemplateID(taxEmailTemplate[0].Id); 
            emailRecord.setOrgWideEmailAddressId(owea[0].Id);
            if(invoiceRecord.Opportunity_Name__r.Owner.Manager.Email != null){
                ccAddress.add(invoiceRecord.Opportunity_Name__r.Owner.Manager.Email);
            }
            
            if(invoiceRecord.Opportunity_Name__r.Owner.Email != null){
                ccAddress.add(invoiceRecord.Opportunity_Name__r.Owner.Email); 
            }
            if(optyEmailRecipsMap.size()>0 && optyEmailRecipsMap.containsKey(invoiceRecord.Opportunity_Name__c)){
                ccAddress.addAll(optyEmailRecipsMap.get(invoiceRecord.Opportunity_Name__c));
            }

            ccAddress.add(Label.set_CC_email);
            
            emailRecord.setToAddresses(new List<String> {invoiceRecord.Contact_Name__r.Email});
            if(ccAddress.size()> 0 ){
                emailRecord.setCcAddresses(ccAddress);
            }
            
            emailRecord.setSaveAsActivity(false); 
            emailRecord.setSaveAsActivity(true);
            emailRecord.setEntityAttachments( new List<String> {pdfFile.ContentDocument.LatestPublishedVersion.Id}); 
            emailRecord.setPlainTextBody(taxEmailTemplate[0].Body);
            emailRecord.setSubject(invoiceType+'Invoice towards service(s) by ICRA Limited – '+ invoiceRecord.Bill_NO__c); 
        }

        return emailRecord;
        
    }



    class InvoiceData{
        public Boolean selectRecord {get;set;}
        public Invoice__c invoiceRecord {get;set;}
        public Transient Messaging.SingleEmailMessage emailRecord {get; private set;} 

        InvoiceData(){ 
            invoiceRecord = new Invoice__c();
            selectRecord = false;
            emailRecord = new Messaging.SingleEmailMessage();
        }
    }
     
}