force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <formula>IF(
AND(
ISPICKVAL(Opportunity_Name__r.Already_Invoiced__c,&apos;Yes&apos;),
Opportunity_Name__r.RecordType.Name ==&apos;Surveillance&apos;),
Opportunity_Name__r.Past_Invoice_Number__c ,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)
),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Initiate Tax Invoice&apos;),
Auto_Generated_Tax_Invoice__c,
NOT(ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;))),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
NOT(ISBLANK(TEXT(Invoice_Status__c))),
NOT(ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)),
OR(
AND(Auto_Generated_Tax_Invoice__c,
ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;)), 
!Auto_Generated_Tax_Invoice__c
)
),Service_Code__c+&apos;/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c +&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),&apos;&apos;))
))</formula>
    <label>Bill No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proforma_Invoice_ok__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice_ok__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When true email will be send to customer with attached PI invoice pdf</description>
    <label>Proforma Invoice ok</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_EndUserProformaInvoice_Notification.cls
global class ICRA_EndUserProformaInvoice_Notification implements Database.Batchable<sObject> {
    List<Opportunity> Opp = new List<Opportunity>();
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Date dueDate = System.today();
        String filter ='Invoice';
        String filter2 ='Proforma Invoice'; 
        String InvoiceQuery = 'SELECT Id, Name,RecordType.Name,Bill_NO__c,Invoice_Created_Date__c,Proforma_Invoice_ok__c,Opportunity_Name__r.RecordType.Name,Invoice_Status__c,Opportunity_Name__r.Owner.Email,Opportunity_Name__r.Proforma_Invoice_ok__c ,Opportunity_Name__r.Owner.Manager.Email, Opportunity_Name__r.OwnerId,Opportunity_Name__r.Owner.Name,Contact_Name__c, Contact_Name__r.Billing_Contact__c,Contact_Name__r.Name, Contact_Name__r.Email FROM Invoice__c WHERE Contact_Name__r.Email != null AND RecordType.Name =:filter AND Invoice_Created_Date__c =: dueDate  AND Invoice_Status__c =: filter2 AND  Opportunity_Name__r.Proforma_Invoice_ok__c = True';
        return Database.getQueryLocator(InvoiceQuery); 
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> InvoiceList){ 
        EmailTemplate[] emailTemplate = [SELECT DeveloperName, Id, Subject, Description, HtmlValue, Body FROM EmailTemplate WHERE DeveloperName = 'End_User_Proforma_Invoice_Notification' LIMIT 1];
        
        Set<Messaging.SingleEmailMessage> emailSet = new set<Messaging.SingleEmailMessage>();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        Map<Id,EmailNotification> emailNotificationMap = new map<Id,EmailNotification>(); 
        
        for(Invoice__c invoiceRecord : InvoiceList){
            
            EmailNotification temp = new EmailNotification();
            temp.recordOwnerName = invoiceRecord.Opportunity_Name__r.Owner.Name; 
            temp.sendTo = invoiceRecord.Contact_Name__r.Email;
            temp.targetObjectId = invoiceRecord.Contact_Name__c;
            temp.templateName = emailTemplate[0].Id;
            temp.sendToMn = invoiceRecord.Opportunity_Name__r.Owner.Manager.Email;
            temp.sendToBd = invoiceRecord.Opportunity_Name__r.Owner.Email;
            emailNotificationMap.put(invoiceRecord.Opportunity_Name__r.OwnerId, temp);
            
            ContentDocumentLink[] pdfFile = [SELECT Id, LinkedEntityId, ContentDocument.LatestPublishedVersion.VersionData,ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp FROM ContentDocumentLink WHERE LinkedEntityId =: invoiceRecord.Id AND ContentDocument.LatestPublishedVersion.Title Like'%Signed%'  order by SystemModstamp DESC LIMIT 1];
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setFileName( invoiceRecord.Bill_No__c + ' - ' + invoiceRecord.Invoice_Created_Date__c +'.pdf');
            Blob Pdfget;
            try { 
                Pdfget  =  pdfFile.size() > 0 ? pdfFile[0].ContentDocument.LatestPublishedVersion.VersionData : Blob.valueOf('No File Found');
                
            } catch (VisualforceException e) {
                Pdfget = Blob.valueOf('Error While Genrating file');
            }
            
            efa.setBody(Pdfget);
            String body1 = emailTemplate[0].Body;
            OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'billing@icraindia.info']; 
            
            if(emailNotificationMap.values().size() > 0){
                
                for(EmailNotification email : emailNotificationMap.values()){
                    
                    Messaging.SingleEmailMessage email_record = new Messaging.SingleEmailMessage();
                    email_record.setTargetObjectId(email.targetObjectId);
                    email_record.setTemplateID(email.templateName); 
                    email_record.setOrgWideEmailAddressId(owea.get(0).Id);
                    email_record.setToAddresses(new List<String> {email.sendTo});
                    email_record.setCcAddresses(new List<String> {email.sendToMn,email.sendToBd});
                    email_record.setSaveAsActivity(false);
                    email_record.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
                    email_record.setPlainTextBody(body1);
                    email_record.setSubject('Proforma Invoice towards service(s) by ICRA Limited – '+ invoiceRecord.Bill_NO__c);
                    emailSet.add(email_record); 
                } 
            }
            
        }
        emailList.addALL(emailSet);
        Messaging.sendEmail(emailList);          
    }  
    global void finish(Database.BatchableContext BC){
        system.debug('/  **** Inovice Batch Job is done ****  /' +BC); 
    }
    
    public class EmailNotification{ 
        String targetObjectId = ''; 
        String templateName = '';
        String recordOwnerName = '';
        String sendTo = ''; 
        String sendToMn = '';
        String sendToBd = '';
        public EmailNotification(){}
    }
    
}