force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <formula>IF(
AND(
ISPICKVAL(Opportunity_Name__r.Already_Invoiced__c,&apos;Yes&apos;),
Opportunity_Name__r.RecordType.Name ==&apos;Surveillance&apos;),
Opportunity_Name__r.Past_Invoice_Number__c ,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)
),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Initiate Tax Invoice&apos;),
Auto_Generated_Tax_Invoice__c,
NOT(ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;))),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
NOT(ISBLANK(TEXT(Invoice_Status__c))),
NOT(ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)),
OR(
AND(Auto_Generated_Tax_Invoice__c,
ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;)), 
!Auto_Generated_Tax_Invoice__c
)
),Service_Code__c+&apos;/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c +&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),&apos;&apos;))
))</formula>
    <label>Bill No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Credit_Note_No__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_No__c</fullName>
    <formula>IF(RecordType.Name == &apos;Credit Note&apos;,IF(ISPICKVAL(Credit_Note_Type__c,&apos;GST Credit Note&apos;),
&apos;CN/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c+&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),
&apos;CCN/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c+&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c)),null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Credit Note No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_SaveInvoicePDF.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-24-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-24-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class ICRA_SaveInvoicePDF {
    public static void saveInvoice(String parentId){
        //Check the parrentId is null or not 
        if(parentId != null && parentId != '' && parentId != 'null' ){

            //creat page refference of Invocie PDF to get the PDF.
            PageReference pdf = new PageReference('/apex/ICRA_Invoice_pdf?id='+parentId);
            String fileName='';

            // Get Invocie record. (Get assigne the file name )
            Invoice__c invoiceRecord = [
                SELECT Id , Name, RecordType.Name,Credit_Note_No__c, Bill_No__c 
                FROM Invoice__c 
                WHERE Id =: parentId
                LIMIT 1
            ]; 

            //If invoice record type is Credite note then file name is equal to Credit note number else Bill number.
            if(invoiceRecord.RecordType.Name == 'Credit Note'){
                fileName = invoiceRecord.Credit_Note_No__c;
            }else{
                fileName =  invoiceRecord.Bill_No__c;
            } 


            // Creat content Version record to store and insert the PDF.
            ContentVersion contentVersionRecord = new ContentVersion();
            contentVersionRecord.ContentLocation = 'S';
            contentVersionRecord.PathOnClient =  fileName+'.pdf';
            contentVersionRecord.Title = fileName;

            //Blod Hold the PDF file content (Binary)
            Blob body;
            try { 
                body = pdf.getContent();

            } catch (VisualforceException e) {
                body = Blob.valueOf('Error While Genrating file');
            }

            contentVersionRecord.VersionData =  body;

            // Insert the file
            insert contentVersionRecord;

            // Get the Information of currently inserted file (This is used to link the file with Invoice Object)
            Id contentVersionID = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersionRecord.Id].ContentDocumentId;

            //Creat refference to link the document (PDF file) to invoice object.
            ContentDocumentLink contentDocument = new ContentDocumentLink();
            // Document ID 
            contentDocument.ContentDocumentId = contentVersionID;
            //Record Id (Invoice Record id )
            contentDocument.LinkedEntityId = parentId;
            contentDocument.ShareType = 'V';  
            contentDocument.Visibility = 'AllUsers';
            
            //Link the file with related object 
            insert contentDocument;
        }
    }
}