force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/UpdateInvoicePDF_Title_Batch.cls
global class UpdateInvoicePDF_Title_Batch implements Database.Batchable<sobject>, Database.Stateful{
    global Database.QueryLocator start(Database.BatchableContext bc){
        string proforma = 'Tax Invoice';
        String soqlquery = 'SELECT Id,Name,Invoice_Status__c FROM Invoice__c';
        soqlquery +=' WHERE Invoice_Status__c =: proforma';
        System.debug('Get query' +soqlquery); 
        return Database.getQueryLocator(soqlquery);
    }
    global void execute(Database.BatchableContext bc, List<Invoice__c> invoiceList){
        List<ContentDocument> cdlistupdate = new List<ContentDocument>();

        Map<Id,Invoice__c> piInvoicemap = new Map<Id,Invoice__c>();
        Map<Id,Invoice__c> taxInvoicemap = new Map<Id,Invoice__c>();
        Map<Id,ContentDocument> contentPDF = new Map<Id,ContentDocument>();
        for(Invoice__c inv : invoiceList){
            if(inv.Invoice_Status__c == 'Tax Invoice'){
                piInvoicemap.put(inv.id,inv);
            }
        }
        
        for(ContentDocumentLink pdffile : [ SELECT Id,LinkedEntityId,ContentDocument.title,ContentDocument.LatestPublishedVersion.VersionData, ContentDocument.LatestPublishedVersion.Id,
                                           ContentDocument.LatestPublishedVersion.Title,ContentDocumentId, SystemModstamp, ContentDocument.LatestPublishedVersion.ContentSize
                                           FROM ContentDocumentLink 
                                           WHERE LinkedEntityId IN: piInvoicemap.keySet() AND 
                                           ContentDocument.LatestPublishedVersion.ContentSize > 1023 AND
                                           (NOT(ContentDocument.LatestPublishedVersion.Title Like'%INV%'))
                                           ORDER BY SystemModstamp DESC LIMIT 1
                                          ]){
                                              
                                              contentPDF.put(pdffile.ContentDocumentId,pdffile.ContentDocument);
                                          }
        
        for(ContentDocument cdd : [SELECT Id,Title FROM ContentDocument WHERE Id =: contentPDF.keySet()]){
            cdd.Title = cdd.Title + ' TAX';
            cdlistupdate.add(cdd);
            system.debug('Tilte '+cdd.Title);
        }
        update cdlistupdate;
    }
    global void finish(Database.BatchableContext bc){}
    
}