force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <summarizedField>Invoice_Line_Item__c.Total_Invoice_Amount_WF__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice_No__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_SaveInvoicePDFBatch.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-24-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-24-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
global class ICRA_SaveInvoicePDFBatch implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext BC){
        String proformaFilter = 'Proforma Invoice';
        String taxInvoice = 'Tax Invoice';
        String recordType = 'Invoice';
        String filter2 = 'To Be Billed';
        String InvoiceQuery = 'SELECT Id, Name,RecordType.Name,Invoice_Status__c,Invoice_Created_Date__c,Total_Invoice_Amount__c,Opportunity_Name__r.Defer_Billing_or_Exit_Case__c FROM Invoice__c WHERE Invoice_Created_Date__c = TODAY AND (Invoice_Status__c =: proformaFilter OR Invoice_Status__c =: taxInvoice) AND Opportunity_Name__r.Defer_Billing_or_Exit_Case__c =:filter2';
        return Database.getQueryLocator(InvoiceQuery);
    }
    
    global void execute(Database.BatchableContext BC, List<Invoice__c> InvoiceList){
        
        for(Invoice__c invoiceRecord : InvoiceList){
            
            ICRA_SaveInvoicePDF.saveInvoice(invoiceRecord.Id);
        }
        
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
   
}