force-app/main/default/objects/Debtor_Invoice__c/Debtor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Debtor Invoice</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Debtor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debtor_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debtor Invoices</relationshipLabel>
    <relationshipName>Debtor_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/BIll_No__c.field-meta.xml
<CustomField>
    <fullName>BIll_No__c</fullName>
    <label>BIll No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Email_Already_Send__c.field-meta.xml
<CustomField>
    <fullName>Email_Already_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Already Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Debtor_Invoice_3to6Months_Controller.cls
public class Debtor_Invoice_3to6Months_Controller {
    
    public String accountID {get;set;}
    
    public list<DebtorInvoiceDetail> getDebtorInvoiceDetail(){
        
        List<Account> accountList;
        List<DebtorInvoiceDetail> debtorInvoiceList = new List<DebtorInvoiceDetail>();
        if(! Test.isRunningTest()){
        accountList = [SELECT Id,Name,Historical_Debtor_Ageing__c,Debtor_Balance_Amount__c,(select Id,Name,Bill_No__c,Invoice_Date__c,Account__c,Account__r.Name,Email_Already_Send__c,Account__r.Debtor_Balance_Amount__c from Debtor_Invoices__r where  Email_Already_Send__c = false)  
                       FROM Account
                       WHERE 
                       Id =: accountID AND
                       Historical_Debtor_Ageing__c > 90 AND
                       Historical_Debtor_Ageing__c <= 180
                       
                      ];
        }else{
                    accountList = [SELECT Id,Name,Historical_Debtor_Ageing__c,Debtor_Balance_Amount__c,(select Id,Name,Bill_No__c,Invoice_Date__c,Account__c,Account__r.Name,Email_Already_Send__c,Account__r.Debtor_Balance_Amount__c from Debtor_Invoices__r where  Email_Already_Send__c = false)  
                                   FROM Account];
        }
        for(Account account : accountList){
            
            for(Debtor_Invoice__c dI : account.Debtor_Invoices__r){
                
                if(account.Id == dI.Account__c){
                    
                    DebtorInvoiceDetail debtor = new DebtorInvoiceDetail();
                    debtor.invoiceDate = dI.Invoice_Date__c;
                    debtor.billNumber = dI.Name;
                    debtor.accountName = dI.Account__r.Name;
                    debtor.totalInvoiceAmount = dI.Account__r.Debtor_Balance_Amount__c;
                    debtorInvoiceList.add(debtor);
                }
            }
        }
          return debtorInvoiceList;        
     }
    
    public class DebtorInvoiceDetail{
        public Date invoiceDate {get;set;}
        public String billNumber {get;set;}
        public String accountName {get;set;}
        public Decimal totalInvoiceAmount {get;set;}
        public DebtorInvoiceDetail(){}
    }
 }