force-app/main/default/objects/Debtor_Invoice__c/Debtor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Debtor Invoice</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Debtor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debtor_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debtor Invoices</relationshipLabel>
    <relationshipName>Debtor_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/BIll_No__c.field-meta.xml
<CustomField>
    <fullName>BIll_No__c</fullName>
    <label>BIll No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Email_Already_Send__c.field-meta.xml
<CustomField>
    <fullName>Email_Already_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Already Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Opportunity_Name__r.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <formula>IF(
AND(
ISPICKVAL(Opportunity_Name__r.Already_Invoiced__c,&apos;Yes&apos;),
Opportunity_Name__r.RecordType.Name ==&apos;Surveillance&apos;),
Opportunity_Name__r.Past_Invoice_Number__c ,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)
),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Initiate Tax Invoice&apos;),
Auto_Generated_Tax_Invoice__c,
NOT(ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;))),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
NOT(ISBLANK(TEXT(Invoice_Status__c))),
NOT(ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)),
OR(
AND(Auto_Generated_Tax_Invoice__c,
ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;)), 
!Auto_Generated_Tax_Invoice__c
)
),Service_Code__c+&apos;/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c +&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),&apos;&apos;))
))</formula>
    <label>Bill No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Used in Credit note PDF and Reports (Convert date to Text)</description>
    <formula>Invoice_No__r.Invoice_Created_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date CN</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <summarizedField>Invoice_Line_Item__c.Total_Invoice_Amount_WF__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice_No__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Invoice_Taxable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Taxable_Amount__c</fullName>
    <label>Total Invoice Taxable Amount</label>
    <summarizedField>Invoice_Line_Item__c.Invoice_Taxable_Amount_copy__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice_No__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_DebtorEmail_1to3_Months_Controller.cls
public class ICRA_DebtorEmail_1to3_Months_Controller {
public  String accountID {get;set;}
    public  List<InvoiceDetail> getInvoiceDetail(){
         List<Invoice__c> invoiceList;
        
         if(! Test.isRunningTest()){
        invoiceList = [
            SELECT Id,Name,Bill_No__c,Invoice_Created_Date__c,Contact_Name__r.Check_Debtor_Email_1_year__c,Total_Invoice_Taxable_Amount__c,Opportunity_Name__r.Debtors_Ageing__c,Contact_Name__c,Contact_Name__r.Account.Name,
            Contact_Name__r.Contact_Debtor_Type__c,Contact_Name__r.Name, Contact_Name__r.Email,Contact_Name__r.AccountId,Account_ID__c,Opportunity_Name__r.ASF_Final_Amount__c,Opportunity_Name__r.AccountId,Opportunity_Name__r.Balance_Amount__c 
            FROM Invoice__c  
            WHERE (Contact_Name__r.Email != null AND 
             Contact_Name__r.Contact_Debtor_Type__c = '90Days' AND
            Opportunity_Name__r.AccountId =: accountID AND
            Contact_Name__r.Debtor_Email__c = 'Yes' AND 
            Opportunity_Name__r.Debtors_Ageing__c >= 1 AND 
            Opportunity_Name__r.Debtors_Ageing__c <= 90)
            
            OR( 
            Contact_Name__r.Email != null AND
            Contact_Name__r.Contact_Debtor_Type__c = '90Days' AND
            Opportunity_Name__r.AccountId =: accountID AND
            Contact_Name__r.Debtor_Email__c = 'Yes' AND
            Contact_Name__r.Account.Historical_Debtor_Ageing__c >= 1 AND 
            Contact_Name__r.Account.Historical_Debtor_Ageing__c <= 90)
         ]; 
         }else{
              invoiceList = [
            SELECT Id,Name,Bill_No__c,Invoice_Created_Date__c,Contact_Name__r.Check_Debtor_Email_1_year__c,Total_Invoice_Taxable_Amount__c,Opportunity_Name__r.Debtors_Ageing__c,Contact_Name__c,Contact_Name__r.Account.Name,
            Contact_Name__r.Contact_Debtor_Type__c,Contact_Name__r.Name, Contact_Name__r.Email,Contact_Name__r.AccountId,Account_ID__c,Opportunity_Name__r.ASF_Final_Amount__c,Opportunity_Name__r.AccountId,Opportunity_Name__r.Balance_Amount__c 
            FROM Invoice__c ]; 
           }
        List<InvoiceDetail> invoiceDetailList = new List<InvoiceDetail>(); 
        
        for(Invoice__c invoiceRecord : invoiceList ){
            InvoiceDetail  invoice = new InvoiceDetail();
            invoice.billNumber = invoiceRecord.Bill_No__c;
            invoice.invoiceDate = invoiceRecord.Invoice_Created_Date__c;
            invoice.accountName=invoiceRecord.Contact_Name__r.Account.Name;
            invoice.totalInvoiceAmount = invoiceRecord.Opportunity_Name__r.Balance_Amount__c;
           
            invoiceDetailList.add(invoice);
              
        }
        List<Debtor_Invoice__c> debtorList;
        if(! Test.isRunningTest()){
        
        debtorList = [SELECT Id,Name,Bill_No__c,Invoice_Date__c,Account__r.Name,Total_Invoice_Amount__c,Account__r.Total_Oustanding_Debtor_Invoice_Amount__c,Account__r.Historical_Debtor_Ageing__c,Account__r.Id,Account__r.Debtor_Balance_Amount__c 
                      FROM Debtor_Invoice__c 
                      WHERE Account__r.Id =: accountID AND
                       Account__r.Contact_Name__r.Email != null AND 
                      Account__r.Contact_Name__r.Contact_Debtor_Type__c = '90Days' AND
                      Account__r.Contact_Name__r.Debtor_Email__c = 'Yes' AND
                      Email_Already_Send__c = false AND 
                      Account__r.Historical_Debtor_Ageing__c >= 1 AND
                      Account__r.Historical_Debtor_Ageing__c <= 90 
                     ];
        }else{
              debtorList = [SELECT Id,Name,Bill_No__c,Invoice_Date__c,Account__r.Name,Total_Invoice_Amount__c,Account__r.Total_Oustanding_Debtor_Invoice_Amount__c,Account__r.Historical_Debtor_Ageing__c,Account__r.Id,Account__r.Debtor_Balance_Amount__c 
                            FROM Debtor_Invoice__c ];
        }
         
        
        for(Debtor_Invoice__c debtorInvoice : debtorList){
            InvoiceDetail  invoice= new InvoiceDetail();
            invoice.billNumber = debtorInvoice.Name;
            invoice.invoiceDate = debtorInvoice.Invoice_Date__c;
            invoice.accountName= debtorInvoice.Account__r.Name;
            invoice.totalInvoiceAmount = debtorInvoice.Account__r.Debtor_Balance_Amount__c;
            invoiceDetailList.add(invoice);
           
        }
         return invoiceDetailList;
      }
    
    public class InvoiceDetail{
        public Date invoiceDate {get;set;}
        public String billNumber {get;set;}
        public String accountName {get;set;}
        public Decimal totalInvoiceAmount {get;set;}
        public InvoiceDetail(){}
        
    }
 }