force-app/main/default/objects/Debtor_Invoice__c/Debtor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Debtor Invoice</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Debtor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debtor_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Debtor Invoices</relationshipLabel>
    <relationshipName>Debtor_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/BIll_No__c.field-meta.xml
<CustomField>
    <fullName>BIll_No__c</fullName>
    <label>BIll No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Email_Already_Send__c.field-meta.xml
<CustomField>
    <fullName>Email_Already_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Already Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Invoice Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_ID__c</fullName>
    <formula>Opportunity_Name__r.AccountId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <formula>IF(
AND(
ISPICKVAL(Opportunity_Name__r.Already_Invoiced__c,&apos;Yes&apos;),
Opportunity_Name__r.RecordType.Name ==&apos;Surveillance&apos;),
Opportunity_Name__r.Past_Invoice_Number__c ,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)
),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Initiate Tax Invoice&apos;),
Auto_Generated_Tax_Invoice__c,
NOT(ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;))),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
NOT(ISBLANK(TEXT(Invoice_Status__c))),
NOT(ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)),
OR(
AND(Auto_Generated_Tax_Invoice__c,
ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;)), 
!Auto_Generated_Tax_Invoice__c
)
),Service_Code__c+&apos;/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c +&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),&apos;&apos;))
))</formula>
    <label>Bill No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Debtor_Type__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Type__c</fullName>
    <label>Debtor Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>90Days</fullName>
            </value>
            <value>
                <fullName>180Days</fullName>
            </value>
            <value>
                <fullName>1year</fullName>
            </value>
            <value>
                <fullName>After 1year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Email_Send_at__c.field-meta.xml
<CustomField>
    <fullName>Email_Send_at__c</fullName>
    <label>Email Send at</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>90Days</fullName>
            </value>
            <value>
                <fullName>180Days</fullName>
            </value>
            <value>
                <fullName>1year</fullName>
            </value>
            <value>
                <fullName>After 1year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Used in Credit note PDF and Reports (Convert date to Text)</description>
    <formula>Invoice_No__r.Invoice_Created_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date CN</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Outstanding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Amount__c</fullName>
    <formula>Opportunity_Name__r.VoD_in_crore__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Invoice_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoice_Amount__c</fullName>
    <label>Total Invoice Amount</label>
    <summarizedField>Invoice_Line_Item__c.Total_Invoice_Amount_WF__c</summarizedField>
    <summaryForeignKey>Invoice_Line_Item__c.Invoice_No__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/EmailReminder_Debtors_Batch_More_1year.cls
global class EmailReminder_Debtors_Batch_More_1year implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        String debtorEmail = 'Yes';
        String debtorType = 'After 1year';
        String  InvoiceQuery ='';
        if(! test.isRunningTest()){
            InvoiceQuery = 'SELECT Id, Name,Bill_No__c,Account_ID__c,Debtor_Type__c,Contact_Name__r.Account.Outstanding_Amount__c,Email_Send_at__c,Total_Invoice_Amount__c,Opportunity_Name__r.Name,Opportunity_Name__r.ASF_Final_Amount__c,Opportunity_Name__r.Debtors_Ageing__c,Contact_Name__c,Contact_Name__r.Check_Debtor_Email_1_year__c,Contact_Name__r.Contact_Debtor_Type__c,Contact_Name__r.Name, Contact_Name__r.Email FROM Invoice__c  WHERE Contact_Name__r.Email != null AND Contact_Name__r.Debtor_Email__c = :debtorEmail AND Opportunity_Name__r.Debtors_Ageing__c > 365 AND Total_Invoice_Amount__c  >= 100000 AND Contact_Name__r.Account.Historical_Debtor_Ageing__c > 365 AND Contact_Name__r.Account.Outstanding_Amount__c > 100000 AND Contact_Name__r.Contact_Debtor_Type__c =: debtorType';
        }else{
            InvoiceQuery = 'SELECT Id, Name,Bill_No__c,Account_ID__c,Debtor_Type__c,Contact_Name__r.Account.Outstanding_Amount__c,Email_Send_at__c,Total_Invoice_Amount__c,Opportunity_Name__r.Name,Opportunity_Name__r.ASF_Final_Amount__c,Opportunity_Name__r.Debtors_Ageing__c,Contact_Name__c,Contact_Name__r.Check_Debtor_Email_1_year__c,Contact_Name__r.Contact_Debtor_Type__c,Contact_Name__r.Name, Contact_Name__r.Email FROM Invoice__c';
        }
        return Database.getQueryLocator(InvoiceQuery);
        
        
    }
    global void execute(Database.BatchableContext BC,List<Invoice__c> InvoiceList){
         Set<Messaging.SingleEmailMessage> emailSet = new set<Messaging.SingleEmailMessage>();
        Set<Id> accountIdSet = new Set<Id>();
        List<Invoice__c> updateDebtorpicklist = new List<Invoice__c>();
        
        for(Invoice__c invoiceRecord : InvoiceList){
            
            if(invoiceRecord.Contact_Name__r.Check_Debtor_Email_1_year__c == false){
                
                Messaging.SingleEmailMessage email_record = new Messaging.SingleEmailMessage();
                email_record.setTargetObjectId(invoiceRecord.Contact_Name__c);  
                
                EmailTemplate [] emailTemplate = [Select Id,Subject,Description,HtmlValue,DeveloperName,Body from EmailTemplate where DeveloperName = 'Debtors_Email_1_year' LIMIT 1];
                if(emailTemplate.size() > 0){
                    email_record.setTemplateID(emailTemplate[0].Id);  
                }  
                email_record.setWhatId(invoiceRecord.Opportunity_Name__r.Id);   
                email_record.setToAddresses(new List<String> {invoiceRecord.Contact_Name__r.Email});
                emailSet.add(email_record);
                accountIdSet.add(invoiceRecord.Contact_Name__r.AccountId);
                invoiceRecord.Debtor_Type__c = 'After 1year';
                invoiceRecord.Email_Send_at__c = 'After 1year';
                invoiceRecord.Contact_Name__r.Check_Debtor_Email_1_year__c = true;
                updateDebtorpicklist.add(invoiceRecord);
            }
            
         }
        
    List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        emailList.addAll(emailSet);
        
        Messaging.sendEmail(emailList);
        List<Account> accountList = new List<Account>();
        for(Account acc : [SELECT Id,Name,Email_Send_at__c FROM Account WHERE Id =: accountIdSet]){
            acc.Email_Send_at__c = 'After 1year';
            accountList.add(acc);
        }
        
        if(accountList.size() > 0){
            update accountList;
        }
        if(updateDebtorpicklist.size() > 0){
            update updateDebtorpicklist;
        }
        List<Debtor_Invoice__c> updateCheckEmailFlag = new  List<Debtor_Invoice__c>();
        
        for(Debtor_Invoice__c updateDebtor : [SELECT Id,Name,Bill_No__c,Email_Already_Send__c,Invoice_Date__c,Account__r.Name,Total_Invoice_Amount__c,Account__r.Total_Oustanding_Debtor_Invoice_Amount__c,Account__r.Historical_Debtor_Ageing__c,Account__r.Id,Account__r.Contact_Name__r.Email,Account__r.Contact_Name__r.Contact_Debtor_Type__c 
                                              FROM Debtor_Invoice__c 
                                              WHERE Account__r.Id =: accountIdSet AND
                                              Email_Already_Send__c = false AND
                                              Account__r.Contact_Name__r.Email != null AND
                                              Account__r.Contact_Name__r.Contact_Debtor_Type__c = 'After 1year' AND
                                              Account__r.Historical_Debtor_Ageing__c > 365 AND
                                              Account__r.Total_Oustanding_Debtor_Invoice_Amount__c > 100000 
                                             ]){ 
                                                  updateDebtor.Email_Already_Send__c = true ;
                                                 updateCheckEmailFlag.add(updateDebtor);
                                              }
        if(updateCheckEmailFlag.size() > 0){
            
            update updateCheckEmailFlag;
        }
     }
    
    
    global void finish(Database.BatchableContext BC){
    }
    
}