force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Addresses</relationshipLabel>
    <relationshipName>Billing_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
                <isActive>false</isActive>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
                <isActive>false</isActive>
                <label>Brunei</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BillingCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Alessandria</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Ancona</fullName>
            </value>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh (New)</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Aosta</fullName>
            </value>
            <value>
                <fullName>Arezzo</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Ascoli Piceno</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Asti</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Avellino</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Bari</fullName>
            </value>
            <value>
                <fullName>Barletta-Andria-Trani</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/GSTN__c.field-meta.xml
<CustomField>
    <fullName>GSTN__c</fullName>
    <label>GSTN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Is_Primary_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Sector__c/fields/Business_Head__c.field-meta.xml
<CustomField>
    <fullName>Business_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/Opportunity_Checker__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/PI_Send__c.field-meta.xml
<CustomField>
    <fullName>PI_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PI Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Triggers_status__c/Triggers_status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To control the status of the triggers</description>
    <label>Triggers_status</label>
</CustomObject>

force-app/main/default/objects/Triggers_status__c/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers_status__c/fields/Fee_Calculation__c.field-meta.xml
<CustomField>
    <fullName>Fee_Calculation__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Fee_Calculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers_status__c/fields/OFAC_Trigger__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OFAC_Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers_status__c/fields/OpportunityTrigger__c.field-meta.xml
<CustomField>
    <fullName>OpportunityTrigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers_status__c/fields/PromotorCompany__c.field-meta.xml
<CustomField>
    <fullName>PromotorCompany__c</fullName>
    <defaultValue>true</defaultValue>
    <label>PromotorCompany</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OFacApproved_Test.cls
@isTest
public class OFacApproved_Test {
   private static final String INVOICEROLE = 'Name on Invoice';
    private static final String EMAILROLE = 'Email Recipient';
    private static final String CONEMAIL = 'testcontactrole@abc.com';
    private static final String ISSUER = 'Issuer';
    private static final String CLOSEDSTAGE = 'Closed Won';
    private static final String FIRSTSTAGE = 'L1 Meeting';
    private static final String NEWBUSINESS = 'New Business';
    private static final String TESTNAME1 = 'ConRoleTest';
    private static final String TESTNAME2 = 'TestNameRole';
 static testMethod void validateBilledOptyLock() {
        try{
        Test.startTest();
            Triggers_status__c tg_status= new Triggers_status__c();
            tg_status.OpportunityTrigger__c= true;
            tg_status.PromotorCompany__c= true;
            tg_status.Fee_Calculation__c= true;
            tg_status.OFAC_Trigger__c= true;
            insert tg_status;
    
            Branch__c branchRecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
            Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            //ICRA_TestDataFactory
            User usrLH = TestFactory.createTestUser1(pf.Id, 'Test FirstName', 'Test LastName',null); 
            usrLH.MobilePhone='1234567890';
            usrLH.Branch__c='Gurugram';
            usrLH.Designation__c='VP';
            usrLH.City='Gurugram';
            update usrLH;
    
            Business_Sector__c businessSector = new Business_Sector__c();
            businessSector.Name = 'Infrastructure';
            businessSector.Business_Head__c =  usrLH.Id; 
            businessSector.OFAC_Approver__c = usrLH.Id; 
            businessSector.Opportunity_Checker__c = usrLH.Id; 
            insert businessSector;

            Account acc =  ICRA_TestDataFactory.CreateAccount(TESTNAME1, ISSUER, null); 
            acc.PAN_Number__c = 'AAACI0218B';
            //acc.GST_Number__c = '24AAACI0218B1ZG';
            acc.ShippingCountry = 'India';
            acc.ShippingState = 'Maharashtra';
            acc.Group_Name__c = 'NA';
            Insert acc;

            Billing_Address__c billingAddr = new Billing_Address__c();
            billingAddr.Name = 'Damco Test 1';                     
            billingAddr.Account_Name__c = Acc.Id;           
            billingAddr.Billing_City__c = 'Mumbai';                 
            billingAddr.BillingCountry__c = 'India';                  
            billingAddr.BillingState__c = 'Maharashtra';                  
            billingAddr.Billing_Street__c = 'Mahrarana Pratap Marg'; 
            billingAddr.GSTN__c = '27AAACI0218B1ZP';               
            billingAddr.Billing_Zip_Postal_Code__c = '554410';        
            billingAddr.Is_Primary_Billing_Address__c = true;      
            insert billingAddr;

            List<Contact> conList = new List<Contact>{TestFactory.getContact(acc.Id,TESTNAME1,TESTNAME1,true),
                                                        TestFactory.getContact(acc.Id,TESTNAME2,TESTNAME1,true)};
            conList[0].Email = CONEMAIL;
            conList[1].Email = CONEMAIL;
            Update conList;
            Opportunity opty = ICRA_TestDataFactory.creatOpportunity(TESTNAME1, NEWBUSINESS, acc.Id); 
            opty.Instrument_type_1__c = 'Non Structured Finance';
            opty.Instrument_type_2__c = 'Rating - Bank Loan Rating';
            opty.Instrument_type_3__c = 'Bank Loan Rating';
            opty.Instrument_type_4__c = 'Bank Loan Rating Fresh';
            opty.Customer_Fee_Type__c = 'Non - Cap';
            opty.StageName = 'L1 Meeting';
            
            insert opty; 
            opty.OFAC_Approved__c=true;
            update opty;
        	List<Opportunity> optyList = [Select Id,AccountId,StageName,Name,CloseDate from Opportunity];
            Invoice__c invoiceRecord  = ICRA_TestDataFactory.createInvoice('Invoice',optyList[0].Id, null,null);
        	invoiceRecord.Invoice_Status__c = 'Tax Invoice';
        	invoiceRecord.PI_Send__c = false;
            insert invoiceRecord;
            optyList[0].StageName = CLOSEDSTAGE;
            OFacApproved_Recursion.isFirstTime=true;
            optyList[0].OFAC_Approved__c =true;
            Update optyList;
            Test.stopTest();
        System.assertEquals(optyList.size(),1);
        }catch(Exception ex){
            System.debug('%%%Exception- '+ex.getMessage());
        }
    }
}