force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/Billing_BvD_ID__c.field-meta.xml
<CustomField>
    <fullName>Billing_BvD_ID__c</fullName>
    <label>Billing BvD ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
                <isActive>false</isActive>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
                <isActive>false</isActive>
                <label>Brunei</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BillingCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Alessandria</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Ancona</fullName>
            </value>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh (New)</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Aosta</fullName>
            </value>
            <value>
                <fullName>Arezzo</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Ascoli Piceno</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Asti</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Avellino</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Bari</fullName>
            </value>
            <value>
                <fullName>Barletta-Andria-Trani</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/GSTN__c.field-meta.xml
<CustomField>
    <fullName>GSTN__c</fullName>
    <label>GSTN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ICRA_BillingAddress_Update_DataOne.cls
@RestResource(urlMapping='/BillingAddressUpdate/*')
global with sharing class ICRA_BillingAddress_Update_DataOne {
    @HttpPost
    global static ICRA_BillingAddress_Update_DataOne.ResponseWrapper billingAddressUpdate(){
        String req= RestContext.request.requestBody.toString();
        ICRA_BillingAddress_Update_DataOne.ResponseWrapper returnValue= new ICRA_BillingAddress_Update_DataOne.ResponseWrapper();
        if(String.isNotBlank(req)){
            try{
                ICRA_BillingAddress_Update_Wrapper billingAddrWrapper= (ICRA_BillingAddress_Update_Wrapper) JSON.deserialize(req, ICRA_BillingAddress_Update_Wrapper.class);
                system.debug('Request Payload==>>'+billingAddrWrapper);
                if(billingAddrWrapper.data[0].billingAddress_ID!=''){
                    List<Billing_Address__c> billingAddrData= [select Id, Billing_Street__c, Billing_City__c, BillingCountry__c, BillingState__c, Billing_Zip_Postal_Code__c, GSTN__c, Billing_BvD_ID__c from Billing_Address__c where Id=:billingAddrWrapper.data[0].billingAddress_ID LIMIT 1];
                    if(billingAddrData!=null && billingAddrData.size()>0){
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].billingStreet))){
                            billingAddrData[0].Billing_Street__c= String.valueOf(billingAddrWrapper.data[0].billingStreet);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].billingCity))){
                            billingAddrData[0].Billing_City__c= String.valueOf(billingAddrWrapper.data[0].billingCity);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].billingCountry))){
                            billingAddrData[0].BillingCountry__c= String.valueOf(billingAddrWrapper.data[0].billingCountry);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].billingState))){
                            billingAddrData[0].BillingState__c= String.valueOf(billingAddrWrapper.data[0].billingState);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].billingPostalCode))){
                            billingAddrData[0].Billing_Zip_Postal_Code__c= String.valueOf(billingAddrWrapper.data[0].billingPostalCode);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].gstn))){
                            billingAddrData[0].GSTN__c= String.valueOf(billingAddrWrapper.data[0].gstn);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].bvdId))){
                            billingAddrData[0].Billing_BvD_ID__c= String.valueOf(billingAddrWrapper.data[0].bvdId);
                        }
                        if(!String.isBlank(String.valueOf(billingAddrWrapper.data[0].billingcurrency))){
                            billingAddrData[0].CurrencyIsoCode= String.valueOf(billingAddrWrapper.data[0].billingcurrency);
                        }
                        update billingAddrData;
                        returnValue.StatusMessage= 'Billing Address Updated Successfully!';
                    }else{
                        returnValue.StatusMessage= 'Record not found';
                    }
                }else{
                    returnValue.StatusMessage= 'Please provide the Billing Address Id in request payload';
                }

            }catch(Exception ex){
                system.debug(ex.getMessage()+'----line no ===>>> '+ex.getLineNumber());
                ICRA_BillingAddress_Update_DataOne.ResponseWrapper returnValueEx= new ICRA_BillingAddress_Update_DataOne.ResponseWrapper();
                returnValueEx.StatusMessage= 'Some error occured while processing the request'+': '+ex.getMessage();
                return returnValueEx;
            }
        }
        return returnValue;
    }
    global class ResponseWrapper{
        //global Integer StatusCode;
        global String StatusMessage;
    }
}