force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Addresses</relationshipLabel>
    <relationshipName>Billing_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
                <isActive>false</isActive>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
                <isActive>false</isActive>
                <label>Brunei</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BillingCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Alessandria</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Ancona</fullName>
            </value>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh (New)</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Aosta</fullName>
            </value>
            <value>
                <fullName>Arezzo</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Ascoli Piceno</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Asti</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Avellino</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Bari</fullName>
            </value>
            <value>
                <fullName>Barletta-Andria-Trani</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/GSTN__c.field-meta.xml
<CustomField>
    <fullName>GSTN__c</fullName>
    <label>GSTN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <description>Defined for the Inter-Branch Manual Invoice record type</description>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-SEZ</fullName>
                <default>true</default>
                <label>Non - SEZ</label>
            </value>
            <value>
                <fullName>SEZ With Tax</fullName>
            </value>
            <value>
                <fullName>SEZ Without Tax</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Inter_Branch_Sequence_MI__c.field-meta.xml
<CustomField>
    <fullName>Inter_Branch_Sequence_MI__c</fullName>
    <label>Inter Branch Sequence MI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Sector__c/fields/Business_Head__c.field-meta.xml
<CustomField>
    <fullName>Business_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/Opportunity_Checker__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/Manual_Invoice__c.object-meta.xml
<CustomObject>
    <label>Manual Invoice</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Manual Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <formula>TEXT( Account_Name__r.Account_Classification__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Manual Invoices</relationshipLabel>
    <relationshipName>Manual_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Manual Invoices (Branch)</relationshipLabel>
    <relationshipName>Manual_Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice_Line_Item__c/Manual_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Manual Invoice Line Item</label>
    <nameField>
        <displayFormat>MINVL-{0000000}</displayFormat>
        <label>Manual Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice_Line_Item__c/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <formula>TEXT(Invoice_No__r.Account_Name__r.Account_Classification__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice_Line_Item__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Manual Invoice Line Items</relationshipLabel>
    <relationshipName>Manual_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Triggers_status__c/Triggers_status__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>To control the status of the triggers</description>
    <label>Triggers_status</label>
</CustomObject>

force-app/main/default/objects/Triggers_status__c/fields/Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Triggers_status__c/fields/InterBranch_Manual_Invoice__c.field-meta.xml
<CustomField>
    <fullName>InterBranch_Manual_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to control the trigger on Manual Invoice</description>
    <label>InterBranch_Manual_Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InterBranch_Manual_Invoice_Test.cls
@isTest
public class InterBranch_Manual_Invoice_Test {
    @isTest
    static void testAssignInterInvoiceNumbers() {

        Triggers_status__c tg_status= new Triggers_status__c();
        tg_status.InterBranch_Manual_Invoice__c= true;
        insert tg_status;

        User username = [SELECT id,name FROM User WHERE Name = 'Damco Admin'];
        List<Manual_Invoice_Line_Item__c> linelist = new List<Manual_Invoice_Line_Item__c>();
        Branch__c branchrecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
        branchrecord.Inter_Branch_Sequence_MI__c = 0;
        update branchrecord;
        Business_Sector__c businessSector = new Business_Sector__c();
        businessSector.Name = 'Infrastructure';
        businessSector.Business_Head__c =  username.Id; 
        businessSector.OFAC_Approver__c = username.Id; 
        businessSector.Opportunity_Checker__c = username.Id; 
        insert businessSector;
        Account accountRecord = ICRA_TestDataFactory.CreateAccount('Test Account','Issuer',branchrecord.Id);
        accountRecord.OFAC_Document_Received__c = true;
        accountRecord.Related_Party__c = 'No';
        accountRecord.Group_Name__c = 'Test Group';
        accountRecord.Account_Status__c = 'Active';
        accountRecord.OFAC_Check__c = true;
        accountRecord.Business_Sector__c = businessSector.Id;
        accountRecord.BillingCity = 'Delhi';
        accountRecord.ShippingCity ='Delhi';
        accountRecord.ShippingStreet ='Office No. 01, 28th Floor';
        accountRecord.ShippingPostalCode ='110001';
        accountRecord.ShippingState ='Delhi';
        accountRecord.ShippingCountry ='India';
        accountRecord.Account_Classification__c = 'SEZ';
        accountRecord.PAN_Number__c = 'ABCDE1234A';
        accountRecord.Constitution_Type_Picklist__c = 'other';
        insert accountRecord;

        Contact contactRecord = ICRA_TestDataFactory.createContact('Test Contact', 'Yes', 'Account Contact', accountRecord.Id);
        insert contactRecord;

        Billing_Address__c billingAddr = new Billing_Address__c();
        billingAddr.Name = 'Damco Test 1';                     
        billingAddr.Account_Name__c = accountRecord.Id;           
        billingAddr.Billing_City__c = 'Gurgaon';                 
        billingAddr.BillingCountry__c = 'India';                  
        billingAddr.BillingState__c = 'Haryana';                  
        billingAddr.Billing_Street__c = 'Mahrarana Pratap Marg'; 
        billingAddr.GSTN__c = '06ABCDE1234A1ZP';               
        billingAddr.Billing_Zip_Postal_Code__c = '554410';        
        billingAddr.Is_Primary_Billing_Address__c = true;      
        insert billingAddr;  


        Manual_Invoice__c invoiceRecord3 = ICRA_TestDataFactory.createManualInvoice('Inter-Branch Invoice', accountRecord.Id, contactRecord.Id,null,null);
        invoiceRecord3.Invoice_Created_Date__c=System.Today();
        invoiceRecord3.Invoice_Date__c=System.Today();
        invoiceRecord3.Billing_Number__C= 0;
        invoiceRecord3.Source_Branch_1__c= branchrecord.Id;
        update invoiceRecord3;
    }
}