force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Addresses</relationshipLabel>
    <relationshipName>Billing_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
                <isActive>false</isActive>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
                <isActive>false</isActive>
                <label>Brunei</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BillingCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Alessandria</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Ancona</fullName>
            </value>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh (New)</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Aosta</fullName>
            </value>
            <value>
                <fullName>Arezzo</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Ascoli Piceno</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Asti</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Avellino</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Bari</fullName>
            </value>
            <value>
                <fullName>Barletta-Andria-Trani</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/GSTN__c.field-meta.xml
<CustomField>
    <fullName>GSTN__c</fullName>
    <label>GSTN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Is_Primary_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Tax_GST_Classification__c.field-meta.xml
<CustomField>
    <fullName>Tax_GST_Classification__c</fullName>
    <label>Tax/GST Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-SEZ</fullName>
                <label>Non - SEZ</label>
            </value>
            <value>
                <fullName>SEZ</fullName>
                <label>SEZ With Tax</label>
            </value>
            <value>
                <fullName>SEZ Without Tax</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Sector__c/fields/Business_Head__c.field-meta.xml
<CustomField>
    <fullName>Business_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/ICRA_Branch__c.field-meta.xml
<CustomField>
    <fullName>ICRA_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICRA Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Business Sectors</relationshipLabel>
    <relationshipName>Business_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/Opportunity_Checker__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ICRA_InvoicePdfController_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-19-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-05-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public with sharing class ICRA_InvoicePdfController_Test {

    @testSetup
    public static void isDataSetup (){
        ICRA_TestDataFactory.loadCustomeSetting();
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        //ICRA_TestDataFactory
        User usrLH = TestFactory.createTestUser1(pf.Id, 'Test FirstName', 'Test LastName',null); 
        usrLH.MobilePhone='1234567890';
        usrLH.Branch__c='Gurugram';
        usrLH.Designation__c='VP';
        usrLH.City='Gurugram';
        update usrLH;
        
        Branch__c branchrecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
        
        Business_Sector__c businessSector = new Business_Sector__c();
        businessSector.Name = 'Infrastructure';
        businessSector.Business_Head__c =  usrLH.Id; 
        businessSector.OFAC_Approver__c = usrLH.Id; 
        businessSector.Opportunity_Checker__c = usrLH.Id; 
        businessSector.ICRA_Branch__c=branchrecord.Id;
        insert businessSector;

        Account accountRecord =  ICRA_TestDataFactory.CreateAccount('Name', 'Issuer', null); 
       // accountRecord.PAN_Number__c = 'AABCU9603R';
       	//accountRecord.GST_Number__c = '24AAACI0218B1ZG';
        accountRecord.Group_Name__c = 'testDamco';
        accountRecord.Branch__c=branchrecord.Id;
        accountRecord.Business_Sector__c= businessSector.Id;
        accountRecord.ShippingCity ='Delhi';
        accountRecord.ShippingStreet ='Office No. 01, 28th Floor';
        accountRecord.ShippingPostalCode ='110001';
        accountRecord.ShippingState ='Delhi';
        accountRecord.ShippingCountry ='India';
        accountRecord.Account_Status__c ='Active'; 
       accountRecord.Constitution_Type_Picklist__c = 'Other';
        accountRecord.OFAC_Check__c =true; 
        Insert accountRecord;

        Billing_Address__c billingAddr = new Billing_Address__c();
        billingAddr.Name = 'Damco Test 1';                     
        billingAddr.Account_Name__c = accountRecord.Id;           
        billingAddr.Billing_City__c = 'Mumbai';                 
        billingAddr.BillingCountry__c = 'India';                  
        billingAddr.BillingState__c = 'Maharashtra';                  
        billingAddr.Billing_Street__c = 'Mahrarana Pratap Marg'; 
        billingAddr.GSTN__c = '27AABCU9603R1ZP';               
        billingAddr.Billing_Zip_Postal_Code__c = '554410';        
        billingAddr.Is_Primary_Billing_Address__c = true; 
                billingAddr.Tax_GST_Classification__c='SEZ';
        insert billingAddr;

        Contact contactRecord = ICRA_TestDataFactory.createContact('name', 'Yes', 'Account Contact', accountRecord.Id); 
        Insert contactRecord;
        Opportunity opportunityRecord = ICRA_TestDataFactory.creatOpportunity('name', 'Surveillance', accountRecord.Id);  
        opportunityRecord.StageName = 'Closed Won'; 
        opportunityRecord.Non_Cooperation_Withdrawal_Reason__c = ''; 
        insert opportunityRecord;
        
        List<OpportunityContactRole> optyConRoles = new List<OpportunityContactRole>{
            new OpportunityContactRole(
                ContactId = contactRecord.Id,
                OpportunityId = opportunityRecord.Id,
                Role = 'Name on Invoice')};
            Insert optyConRoles;
        Invoice__c invoiceRecord  = ICRA_TestDataFactory.createInvoice('Invoice',opportunityRecord.Id, null,null); 
        insert invoiceRecord; 
        Invoice_Line_Item__c invoiceLineRecord_A =  ICRA_TestDataFactory.createInvoiceLineItem(invoiceRecord.Id, opportunityRecord.Id); 
        Invoice_Line_Item__c invoiceLineRecord_B = ICRA_TestDataFactory.createInvoiceLineItem(invoiceRecord.Id, opportunityRecord.Id);
    }
    
    @isTest
    public static void InvoicePdfControllerTest(){
        Invoice__c invoice = [SELECT Id, Name FROM Invoice__c LIMIT 1];         
        PageReference pageRef = Page.ICRA_Invoice_pdf;
        ApexPages.currentPage().getParameters().put('id',invoice.Id);  
        ICRA_InvoicePdfController invoicePdf = new ICRA_InvoicePdfController(new ApexPages.StandardController(invoice));
        invoicePdf.savePDF();   

    }
    
    
}