force-app/main/default/objects/Billing_Address__c/Billing_Address__c.object-meta.xml
<CustomObject>
    <label>Billing Address</label>
    <nameField>
        <label>Billing Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Address__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Addresses</relationshipLabel>
    <relationshipName>Billing_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Billing_Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal_Code__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
                <isActive>false</isActive>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Indian Ocean Territory</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
                <isActive>false</isActive>
                <label>Brunei</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <label>Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BillingCountry__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Agrigento</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>Alessandria</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Ancona</fullName>
            </value>
            <value>
                <fullName>Andaman and Nicobar Islands</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Andhra Pradesh (New)</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Aosta</fullName>
            </value>
            <value>
                <fullName>Arezzo</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Ascoli Piceno</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Asti</fullName>
            </value>
            <value>
                <fullName>Australian Capital Territory</fullName>
            </value>
            <value>
                <fullName>Avellino</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Bari</fullName>
            </value>
            <value>
                <fullName>Barletta-Andria-Trani</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/GSTN__c.field-meta.xml
<CustomField>
    <fullName>GSTN__c</fullName>
    <label>GSTN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Is_Primary_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Billing_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Billing Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Address__c/fields/Tax_GST_Classification__c.field-meta.xml
<CustomField>
    <fullName>Tax_GST_Classification__c</fullName>
    <label>Tax/GST Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-SEZ</fullName>
                <label>Non - SEZ</label>
            </value>
            <value>
                <fullName>SEZ</fullName>
                <label>SEZ With Tax</label>
            </value>
            <value>
                <fullName>SEZ Without Tax</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/Business_Sector__c.object-meta.xml
<CustomObject>
    <label>Business Sector</label>
    <nameField>
        <label>Business Sector</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Sector__c/fields/Business_Head__c.field-meta.xml
<CustomField>
    <fullName>Business_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/ICRA_Branch__c.field-meta.xml
<CustomField>
    <fullName>ICRA_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICRA Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Business Sectors</relationshipLabel>
    <relationshipName>Business_Sectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/OFAC_Approver__c.field-meta.xml
<CustomField>
    <fullName>OFAC_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OFAC Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Sector__c/fields/Opportunity_Checker__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Business_Sectors1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commercial_Head_Details__c/Commercial_Head_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Commercial Head Details</label>
</CustomObject>

force-app/main/default/classes/PricingApprovalMandatesTest.cls
/*********************************************************************************************
ClassName -   PricingApprovalMandatesTest
Description - Test calss for code coverage of PricingApprovalMandates Batch,Scheduler & Controller
*********************************************************************************************/
@isTest(SeeAllData=false)
private class PricingApprovalMandatesTest {
    private static final String NEWBUSINESS = 'New Business';
    private static final String TESTNAME1 = 'Pricing Test';
    private static final String TESTEMAIL = 'testPricing@abc.com';
    private static final String ICGSTR = 'ICG';
    private static final String SECGSTR = 'SECG';
//Test setup
    @testSetup 
    static void testSetup(){
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        //create branch
        User usrLH = TestFactory.createTestUser1(pf.Id, 'Test FirstName', 'Test LastName',null); 
        usrLH.MobilePhone='1234567890';
        usrLH.Branch__c='Gurugram';
        usrLH.Designation__c='VP';
        usrLH.City='Gurugram';
        update usrLH;
        Branch__c B=TestFactory.generateBranch('Mumbai');
        // create Account
        Business_Sector__c businessSector = new Business_Sector__c();
        businessSector.Name = 'Infrastructure';
        businessSector.ICRA_Branch__c=B.id;
        businessSector.Business_Head__c =  usrLH.Id; 
        businessSector.OFAC_Approver__c = usrLH.Id; 
        businessSector.Opportunity_Checker__c = usrLH.Id; 
        insert businessSector;
        Account acc =  ICRA_TestDataFactory.CreateAccount(TESTNAME1, 'Issuer', null); 
        acc.Classification__c = SECGSTR;
        acc.PAN_Number__c = 'AAACI0218B';
        //acc.GST_Number__c = '24AAACI0218B1ZG';
        acc.Branch__c=B.id;
        acc.Group_Name__c = 'N/a';
        acc.Business_Sector__c= businessSector.Id;
        Acc.ShippingCity ='Delhi';
        Acc.ShippingStreet ='Office No. 01, 28th Floor';
        Acc.ShippingPostalCode ='110001';
        Acc.ShippingState ='Delhi';
        Acc.ShippingCountry ='India';
        Acc.Ofac_check__c=true;
        Acc.Account_Status__c ='Active';
        acc.Related_Party__c='No';
        Acc.OFAC_Document_Received__c=true;
        Acc.Customer_Fee_Type__c='Non - Cap';
        Acc.Constitution_Type_Picklist__c='Other';
        upsert acc;

        Billing_Address__c billingAddr = new Billing_Address__c();
        billingAddr.Name = 'Damco Test 1';                     
        billingAddr.Account_Name__c = Acc.Id;           
        billingAddr.Billing_City__c = 'Mumbai';                 
        billingAddr.BillingCountry__c = 'India';                  
        billingAddr.BillingState__c = 'Maharashtra';                  
        billingAddr.Billing_Street__c = 'Mahrarana Pratap Marg'; 
        billingAddr.GSTN__c = '27AAACI0218B1ZP';               
        billingAddr.Billing_Zip_Postal_Code__c = '554410';        
        billingAddr.Is_Primary_Billing_Address__c = true;     
        billingAddr.Tax_GST_Classification__c='Non-Sez';
        insert billingAddr;

        Contact con = TestFactory.getContact(acc.Id,TESTNAME1,TESTNAME1,true); 
        //Opportunity opty = ICRA_TestDataFactory.creatOpportunity(TESTNAME1, 'New Business', acc.Id);
        List<Opportunity> opty = TestFactory.generateOppsForAccount(acc.Id,10000,1);
        opty[0].Pricing_Auto_Approved__c = true;
        opty[0].Customer_Fee_Type__c = 'Non - Cap';
        opty[0].StageName = 'L1 Meeting';
        upsert opty;
        insert new List<Commercial_Head_Details__c>{new Commercial_Head_Details__c(Name = 'ICG',Email__c = 'test1@abc.zxc'),
            										new Commercial_Head_Details__c(Name = 'SECG',Email__c = 'test2@abc.zxc')};
    }
//Test method
    static testMethod void validateSECGApproval() {
        Test.startTest();
        String chron = '0 0 23 * * ?';
        Opportunity opty = [Select Id from Opportunity limit 1];
        PricingApprovalMandatesBatch batch = new PricingApprovalMandatesBatch(new Set<Id>{opty.Id});
        Database.executebatch(batch,200);

        PricingApprovalMandatesScheduler testSche = new PricingApprovalMandatesScheduler();
        String jobId = system.schedule('Test status Check', chron, testsche );
        CronTrigger ct = [Select id , CronExpression from CronTrigger where id = :jobId];
        Test.stopTest();
        System.assertEquals(chron,ct.CronExpression); 
    }
//Test method
    static testMethod void validateICGApproval() {
        Test.startTest();
        List<Account> acc = [SELECT Id,Classification__c FROM Account Limit 1];
        acc[0].Classification__c = ICGSTR;
        upsert acc;
        PricingApprovalMandatesBatch batch = new PricingApprovalMandatesBatch();
        Database.executebatch(batch,200);
        Test.stopTest();
        System.assertEquals(acc.size(),1); 
    }
//Test method
	static testMethod void validateController() {
        Test.startTest();
        List<Account> acc = [SELECT Id,Classification__c FROM Account Limit 1];
        PricingApprovalMandatesController.approvMandates(acc[0].Classification__c+'/'+System.Today().month()+'/'+System.Today().year());
        Opportunity opp = [Select Id,StageName,Pricing_Not_Auto_Approved__c from Opportunity Limit 1];
        opp.StageName = 'Negotiation';
        opp.Pricing_Not_Auto_Approved__c = true;
        update opp;
        manualPricingApprovalController.getOpportunity(null);
        manualPricingApprovalController.resetApproval(opp.Id);
        manualPricingApprovalController.updateApprovalFields(opp.Id);
        try{
        manualPricingApprovalController.invokeApprovalProcess(opp.Id);            
        }catch(Exception ex){
            System.debug('$$$$$'+ex.getMessage());
        }
        Test.stopTest();
        System.assertEquals(acc.size(),1); 
	}
}