force-app/main/default/objects/Payment_Receipt__c/Payment_Receipt__c.object-meta.xml
<CustomObject>
    <label>Payment Receipt</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Payment Receipt  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Receipt__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>IF( Opportunity__r.Account.RecordType.Name  == &apos;Investors &amp; Intermediary&apos;,
Opportunity__r.Account.ShippingStreet &amp;  BR()
&amp; Opportunity__r.Account.ShippingCity &amp;  BR()
&amp; Opportunity__r.Account.ShippingState &amp;  BR()
&amp; Opportunity__r.Account.ShippingCountry &amp;  BR()
&amp; Opportunity__r.Account.ShippingPostalCode ,
 Opportunity__r.BillingAddress__r.Billing_Street__c &amp;  BR()
&amp; Opportunity__r.BillingAddress__r.Billing_City__c &amp;  BR()
&amp; TEXT(Opportunity__r.BillingAddress__r.BillingState__c) &amp;  BR()
&amp; TEXT(Opportunity__r.BillingAddress__r.BillingCountry__c) &amp;  BR() 
&amp;  Opportunity__r.BillingAddress__r.Billing_Zip_Postal_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Base_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Base_Fee_Amount__c</fullName>
    <formula>Gross_Amount__c -( IGST_Payable__c + CGST_Payable__c + SGST_UTGST_Payable__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Base/Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/CGST_Payable__c.field-meta.xml
<CustomField>
    <fullName>CGST_Payable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CGST Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/CGST_Rate__c.field-meta.xml
<CustomField>
    <fullName>CGST_Rate__c</fullName>
    <formula>IF( Account_Classification__c == &apos;Non-SEZ&apos;,
IF( AND(Opportunity__r.Account.RecordType.Name ==&apos;Issuer&apos;,
 TEXT(Opportunity__r.BillingAddress__r.BillingState__c) == TEXT(Opportunity__r.Account.Branch__r.State__c)
) , 0.09,
IF(AND(Opportunity__r.Account.RecordType.Name ==&apos;Investors &amp; Intermediary&apos;,
Opportunity__r.Account.ShippingState == TEXT(Opportunity__r.Account.Branch__r.State__c))
, 0.09,
0)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CGST Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <formula>IF(Opportunity__r.Bill_To__c != null,Opportunity__r.Bill_To__r.Name,Opportunity__r.Account.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <formula>Payment_Receipt_Created_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Customer_GSTIN__c.field-meta.xml
<CustomField>
    <fullName>Customer_GSTIN__c</fullName>
    <formula>Opportunity__r.BillingAddress__r.GSTN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer GSTIN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Customer_State__c.field-meta.xml
<CustomField>
    <fullName>Customer_State__c</fullName>
    <formula>IF( Opportunity__r.Account.RecordType.Name == &apos;Investors &amp; Intermediary&apos;, Opportunity__r.Account.ShippingState , TEXT(Opportunity__r.BillingAddress__r.BillingState__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Customer_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_State_Code__c</fullName>
    <formula>Opportunity__r.Account.State_Code__c</formula>
    <label>Customer State Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Date_of_Cheque_DD__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Cheque_DD__c</fullName>
    <label>Date of Cheque/DD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Date_of_Transfer_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Transfer_Receipt__c</fullName>
    <label>Date of Transfer/Receipt</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <formula>Opportunity__r.Account.Email_Auditor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fee_Amount__c</fullName>
    <label>Fee Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Gross_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Amount__c</fullName>
    <label>Gross Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/GST_No__c.field-meta.xml
<CustomField>
    <fullName>GST_No__c</fullName>
    <formula>Opportunity__r.BillingAddress__r.GSTN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GST No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/IGST_Payable__c.field-meta.xml
<CustomField>
    <fullName>IGST_Payable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IGST Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/IGST_Rate__c.field-meta.xml
<CustomField>
    <fullName>IGST_Rate__c</fullName>
    <formula>IF( Account_Classification__c == &apos;Non-SEZ&apos;,
IF( Opportunity__r.Account.RecordType.Name ==&apos;Issuer&apos;,
IF(TEXT(Opportunity__r.BillingAddress__r.BillingState__c) &lt;&gt; TEXT(Opportunity__r.Account.Branch__r.State__c),
0.18,
0),
IF(Opportunity__r.Account.RecordType.Name ==&apos;Investors &amp; Intermediary&apos;,
IF(Opportunity__r.Account.ShippingState &lt;&gt; TEXT(Opportunity__r.Account.Branch__r.State__c),
0.18,
0),
0)),
IF(Account_Classification__c == &apos;SEZ&apos;,0.18,0))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IGST Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/IGST_Realisable__c.field-meta.xml
<CustomField>
    <fullName>IGST_Realisable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IGST Realisable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Is_Advance__c.field-meta.xml
<CustomField>
    <fullName>Is_Advance__c</fullName>
    <formula>IF(ISBLANK(Invoice_No__c),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Advance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Name_of_Drawee_Bank__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Drawee_Bank__c</fullName>
    <label>Name of Drawee Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Net_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Amount__c</fullName>
    <formula>Gross_Amount__c    -  Tax_at_source_deducted_by_client_TDS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Payment Receipts</relationshipLabel>
    <relationshipName>Payment_Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <formula>Opportunity__r.Account.PAN_Number__c</formula>
    <label>PAN No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>Electronic Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Phone_No__c.field-meta.xml
<CustomField>
    <fullName>Phone_No__c</fullName>
    <formula>Opportunity__r.Account.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Receipt_No__c</fullName>
    <formula>IF( Is_Advance__c == TRUE , &apos;AD/&apos;+Opportunity__r.Account.Branch__r.Branch_Code__c+&apos;/&apos;+Text(YEAR( TODAY() ) )+&apos;/&apos;+ RIGHT(Name, 4), &apos;PR/&apos;+Opportunity__r.Account.Branch__r.Branch_Code__c+&apos;/&apos;+Text(YEAR( TODAY() ) )+&apos;/&apos;+ RIGHT(Name, 4))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receipt No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <formula>IF( Opportunity__r.RecordType.Name == &apos;Surveillance&apos;, &apos;RS&apos;, IF( ISPICKVAL( Opportunity__r.Business_Segment__c , &quot;Research&quot;),&apos;SR&apos;,&apos;RF&apos; ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/SGST_Rate__c.field-meta.xml
<CustomField>
    <fullName>SGST_Rate__c</fullName>
    <formula>IF( Account_Classification__c == &apos;Non-SEZ&apos;,
IF( AND(Opportunity__r.Account.RecordType.Name ==&apos;Issuer&apos;,
TEXT(Opportunity__r.BillingAddress__r.BillingState__c) == TEXT(Opportunity__r.Account.Branch__r.State__c)
) , 0.09,
IF(AND(Opportunity__r.Account.RecordType.Name ==&apos;Investors &amp; Intermediary&apos;,
Opportunity__r.Account.ShippingState == TEXT(Opportunity__r.Account.Branch__r.State__c))
, 0.09,
0)),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SGST Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/SGST_UTGST_Payable__c.field-meta.xml
<CustomField>
    <fullName>SGST_UTGST_Payable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SGST/UTGST Payable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/SGST_UTGST_Realisable__c.field-meta.xml
<CustomField>
    <fullName>SGST_UTGST_Realisable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>SGST/UTGST Realisable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/TAN_No__c.field-meta.xml
<CustomField>
    <fullName>TAN_No__c</fullName>
    <formula>Opportunity__r.Account.TAN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TAN No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Tax_at_source_deducted_by_client_TDS__c.field-meta.xml
<CustomField>
    <fullName>Tax_at_source_deducted_by_client_TDS__c</fullName>
    <label>Tax at Source Deducted By Client (TDS)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Total_Taxable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Taxable_Amount__c</fullName>
    <formula>CGST_Payable__c  +  IGST_Payable__c  +  SGST_UTGST_Payable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Taxable Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Receipt__c/fields/Transaction_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Reference_Number__c</fullName>
    <label>Transaction Reference Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ICRA_PaymentReceiptPdfController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-26-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   02-04-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class ICRA_PaymentReceiptPdfController {
    
    public PaymentReceipt paymentReceiptPage{get;set;}
    public Boolean isError {get;set;}

    public ICRA_PaymentReceiptPdfController (ApexPages.StandardController controller){
        paymentReceiptPage = new PaymentReceipt();
        isError = false;

        try {            
       
            //Get current Record ID 
            String recordId = ''+ApexPages.currentPage().getParameters().get('id');

            if(recordId != 'null' && recordId != '' && recordId != null ){
                paymentReceiptPage.paymentReceiptRecord = [
                    SELECT Address__c, Base_Fee_Amount__c, CGST_Payable__c, Company_Name__c, Created_Date__c, Date_of_Cheque_DD__c, Date_of_Transfer_Receipt__c, 
                        Email_ID__c, Fee_Amount__c, Financial_Year__c, GST_No__c, Gross_Amount__c, IGST_Payable__c, IGST_Realisable__c, Is_Advance__c, 
                        Name_of_Drawee_Bank__c, Net_Amount__c, Opportunity__r.Account.Name, Payment_Method__c, PAN_No__c, Name, Phone_No__c, SGST_UTGST_Payable__c, 
                        SGST_UTGST_Realisable__c, TAN_No__c, Tax_at_source_deducted_by_client_TDS__c, Transaction_Reference_Number__c, Service_Code__c,
                        Opportunity__r.Account.Branch__r.Branch_Code__c, Opportunity__r.Account.Branch__r.Name, Opportunity__r.Account.Branch__r.City__c, 
                        Opportunity__r.Account.Branch__r.Country__c, Opportunity__r.Account.Branch__r.GSTIN__c, Opportunity__r.Account.Branch__r.PAN__c, 
                        Opportunity__r.Account.Branch__r.Id, Opportunity__r.Account.Branch__r.State__c, Opportunity__r.Account.Branch__r.State_Code__c, Opportunity__r.Narration_for_Invoice__c,
                        Opportunity__r.Account.Branch__r.Street__c, Opportunity__r.Account.Branch__r.Zip_Postal_Code__c, CurrencyIsoCode, Total_Taxable_Amount__c,
                        Opportunity__r.Account.Branch__r.Telephone__c , Opportunity__r.AccountId, Customer_State__c,Customer_State_Code__c,Customer_GSTIN__c,Receipt_No__c,
                        CGST_Rate__c, IGST_Rate__c, SGST_Rate__c, Opportunity__r.Account.Branch__r.Authorized_Signatory__r.Designation__c, Opportunity_Record_Type__c,
                        Opportunity__r.Account.Branch__r.Authorized_Signatory__r.Email, Opportunity__r.Account.Branch__r.Authorized_Signatory__r.Name,SAC_HSN__c, Receipt_Voucher_Number__c,
                   Opportunity__r.Instrument_type_4__c,Opportunity__r.Business_Segment__c,Opportunity__r.Recordtype.Name FROM Payment_Receipt__c 
                    WHERE id =: recordId
                    LIMIT 1
                ];
            }

            //if Account id is not equal to null then fetch the account related contact where billing contact is Yes (Recent created).
            if(paymentReceiptPage.paymentReceiptRecord.Opportunity__r.AccountId != null){
                
                paymentReceiptPage.contactRecord = [
                    SELECT Phone, Account.Id, Designation__c, Department, Name, Billing_Contact__c 
                    FROM Contact
                    WHERE  Account.Id =: paymentReceiptPage.paymentReceiptRecord.Opportunity__r.AccountId 
                        AND Billing_Contact__c ='Yes' 
                    ORDER BY CreatedDate DESC
                    LIMIT 1
                ];
            }


            /**
             * Bank Account Setting is custom setting the hold the current account details.
             */
            paymentReceiptPage.bankAccountDetails = [
                SELECT Bank_Address__c, Bank_Name__c, Current_Account_No__c, RTGS_IFSC__c 
                FROM Bank_Account_Setting__c
                LIMIT 2
            ];


            /**
             * Invoice Footer Setting is custom setting the hold the invoice footer details.
             */
            paymentReceiptPage.invoiceFooter = [
                SELECT CIN__c, HelpDesk__c, Registered_Office__c, Telephone__c, Website__c, Email__c
                FROM Invoice_Footer_Setting__c 
                LIMIT 1
            ];

            // if Payment or contact record is null then update the isEoor flag to show error on page 
            if(paymentReceiptPage.paymentReceiptRecord != null && paymentReceiptPage.contactRecord != null){
                isError =  false;
            }else{
                isError = true;
            }
        }catch (Exception ex) {
            isError = true;
            System.debug('========= Exception==========: '+ex);
        }
    }


    /**
     * Method Name : SavePDF
     * Param : None
     * Description : Use to save the pdf file. (Attachetd the file to Invocie Object)
     * 
     */
    public PageReference  savePDF( ) {
        
        //Get the System current date
        DateTime todaysDate = System.today();
        String todayDate = todaysDate.format('yyyy-MM-dd');

        //Get the current record Id 
        String parentId = ApexPages.currentPage().getParameters().get('id');  
        String fileName = '';

        //Check the parrentId is null or not 
        if(parentId != null && parentId != '' && parentId != 'null' ){

            //creat page refference of Payment Receipt PDF to get the PDF.
            PageReference pdf = new PageReference('/apex/ICRA_PaymentReceipt_pdf?id='+parentId);
            
            // Get Payment Receipt record. (Get assigne the file name )
            Payment_Receipt__c PaymentReceipt = [
                SELECT Id , Name 
                FROM Payment_Receipt__c 
                WHERE Id =: parentId
                LIMIT 1
            ];  

            fileName =  PaymentReceipt.Name;

            // Creat content Version record to store and insert the PDF.
            ContentVersion contentVersionRecord = new ContentVersion();
            contentVersionRecord.ContentLocation = 'S';  
            contentVersionRecord.PathOnClient =  fileName+todayDate+'.pdf';
            contentVersionRecord.Title = fileName+'-'+todayDate ;


            //Blod Hold the PDF file content (Binary)
            Blob body;
            try { 
                body = pdf.getContent();

            } catch (VisualforceException e) {
                body = Blob.valueOf('Error While Genrating file');
            }
            contentVersionRecord.VersionData =  body; 

            // Insert the file
            insert contentVersionRecord;

            // Get the Information of currently inserted file (This is used to link the file with Invoice Object)
            Id contentVersionID = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersionRecord.Id].ContentDocumentId; 

            //Creat refference to link the document (PDF file) to invoice object.
            ContentDocumentLink contentDocument = new ContentDocumentLink();

             // Document ID 
            contentDocument.ContentDocumentId = contentVersionID;

             //Record Id (Invoice Record id )
            contentDocument.LinkedEntityId = parentId;  
            contentDocument.ShareType = 'V';  
            contentDocument.Visibility = 'AllUsers';

            //Link the file with related object 
            insert contentDocument;
        }

        //redirect to PDF file.
        return new PageReference('/apex/ICRA_PaymentReceipt_pdf?id='+parentId);        
    }

      

     //Wrapper class for pdf page
    public class PaymentReceipt{
       public Payment_Receipt__c  paymentReceiptRecord  {get;set;} 
       public List<Bank_Account_Setting__c> bankAccountDetails {get;set;} 
       public Contact contactRecord {get;set;}
       public Invoice_Footer_Setting__c invoiceFooter {get;set;}

       public PaymentReceipt(){
           paymentReceiptRecord = new Payment_Receipt__c();  
           bankAccountDetails = new List<Bank_Account_Setting__c>();    
           contactRecord = new Contact();      
           invoiceFooter = new Invoice_Footer_Setting__c();
       }       
    }   
}