force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <formula>IF(
AND(
ISPICKVAL(Opportunity_Name__r.Already_Invoiced__c,&apos;Yes&apos;),
Opportunity_Name__r.RecordType.Name ==&apos;Surveillance&apos;),
Opportunity_Name__r.Past_Invoice_Number__c ,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)
),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
ISPICKVAL(Invoice_Status__c,&apos;Initiate Tax Invoice&apos;),
Auto_Generated_Tax_Invoice__c,
NOT(ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;))),
Name,

IF(
AND(
RecordType.Name ==&apos;Invoice&apos;,
NOT(ISBLANK(TEXT(Invoice_Status__c))),
NOT(ISPICKVAL(Invoice_Status__c,&apos;Proforma Invoice&apos;)),
OR(
AND(Auto_Generated_Tax_Invoice__c,
ISPICKVAL(Initiate_Tax_Invoice_Status__c,&apos;ITI Approved&apos;)), 
!Auto_Generated_Tax_Invoice__c
)
),Service_Code__c+&apos;/&apos;+Opportunity_Name__r.Opp_ICRA_Branch__r.Branch_Code__c +&apos;/&apos;+Bill_Year__c+&apos;/&apos;+TEXT(Billing_Number__c),&apos;&apos;))
))</formula>
    <label>Bill No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Created_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IRN_Number__c.field-meta.xml
<CustomField>
    <fullName>IRN_Number__c</fullName>
    <label>IRN Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{0000000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Bill_No__c.field-meta.xml
<CustomField>
    <fullName>Bill_No__c</fullName>
    <label>Bill No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>to store the Contact Name on Invoice</description>
    <formula>Invoice_No__r.Contact_Name__r.FirstName +&apos; &apos;+ Invoice_No__r.Contact_Name__r.LastName</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <formula>TEXT( Invoice_No__r.Invoice_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice  Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PWC_Test_Response__mdt/PWC_Test_Response__mdt.object-meta.xml
<CustomObject>
    <label>PWC Test Response</label>
    <pluralLabel>PWC Test Responses</pluralLabel>
</CustomObject>

force-app/main/default/objects/PWC_Test_Response__mdt/fields/Error_Response__c.field-meta.xml
<CustomField>
    <fullName>Error_Response__c</fullName>
    <label>Error Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ICRA_GenerateIRNTest.cls
@isTest
public with sharing class ICRA_GenerateIRNTest {
    private class RestMock implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            PWC_Test_Response__mdt[] response1=[Select Response__c from PWC_Test_Response__mdt];
            String fullJson = response1[0].Response__c;
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    
    private class RestMockError implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            PWC_Test_Response__mdt[] responseError=[Select Error_Response__c from PWC_Test_Response__mdt];
            String fullJson = responseError[0].Error_Response__c;
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }
    
    private class RestMockServerError implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"message": "Endpoint request timed out"}';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(504);
            return res;
        }
    }
    
    @isTest
    public static void GenerateIRNTest() {
        List<Invoice__c>invlist=new List<Invoice__c>();
        Branch__c branchrecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
        Account accountReccord = ICRA_TestDataFactory.CreateAccount('Test Account','Issuer',branchrecord.Id);
        Insert accountReccord;
        
        Opportunity opportunityRecord = ICRA_TestDataFactory.creatOpportunity('Test Opportunnity', 'Surveillance', accountReccord.Id);
         opportunityRecord.Instrument_type_1__c = 'Non Structured Finance';
        opportunityRecord.Instrument_type_2__c = 'Rating - Bank Loan Rating';
        opportunityRecord.Instrument_type_3__c = 'Bank Loan Rating';
        opportunityRecord.Instrument_type_4__c = 'Bank Loan Rating';
        opportunityRecord.Billing_Start_Date__c = System.today();
        opportunityRecord.Billing_End_Date__c = System.today().addYears(1); 
        opportunityRecord.ASF_Final_Amount__c = 0; 
        
        
        insert opportunityRecord;
        Invoice__c invoiceRecord = ICRA_TestDataFactory.createInvoice('Invoice',opportunityRecord.Id,null,null);
        insert invoiceRecord;
        
        Invoice_Line_Item__c invl = ICRA_TestDataFactory.createInvoiceLineItem(invoiceRecord.Id, opportunityRecord.Id);
        
        invlist.add(invoiceRecord);
        if(invlist.size() > 0){
        update invlist;
        }
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        ICRA_GenerateIRN.InvokeIRN(invlist);
        Test.stopTest();
    }
    
    @isTest
    public static void BatchTest() {
        List<Invoice__c>invlist=new List<Invoice__c>();
        Branch__c branchrecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
        
        Account accountReccord = ICRA_TestDataFactory.CreateAccount('Test Account1','Issuer',branchrecord.Id);
        Insert accountReccord;
        
        Contact contactRecord = ICRA_TestDataFactory.createContact('Testing Contact','Yes','Account Contact',accountReccord.Id);
        insert contactRecord;
        
        Opportunity opportunityRecord = ICRA_TestDataFactory.creatOpportunity('Test Opportunnity1', 'Surveillance', accountReccord.Id);
          opportunityRecord.Instrument_type_1__c = 'Non Structured Finance';
        opportunityRecord.Instrument_type_2__c = 'Rating - Bank Loan Rating';
        opportunityRecord.Instrument_type_3__c = 'Bank Loan Rating';
        opportunityRecord.Instrument_type_4__c = 'Bank Loan Rating';
        opportunityRecord.Billing_Start_Date__c = System.today();
        opportunityRecord.Billing_End_Date__c = System.today().addYears(1);
        opportunityRecord.ASF_Final_Amount__c = 0; 
        insert opportunityRecord;
        
        Invoice__c invoiceRecord = ICRA_TestDataFactory.createInvoice('Invoice',opportunityRecord.Id,null,'Tax Invoice');
        invoiceRecord.Invoice_Created_Date__c = system.today();
        invoiceRecord.Contact_Name__c = contactRecord.Id;
        insert invoiceRecord;
        
        Invoice_Line_Item__c invl = ICRA_TestDataFactory.createInvoiceLineItem(invoiceRecord.Id, opportunityRecord.Id);
        
        invlist.add(invoiceRecord);
       if(invlist.size() > 0){
        update invlist;
       }
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new RestMock());
        ICRA_GenerateIRNandQRBatch testbatch = new ICRA_GenerateIRNandQRBatch();
        Database.executeBatch(testbatch,1);
        Test.stopTest();
    }
    
    @isTest
    public static void GenerateIRNTest1() {
        List<Invoice__c>invlist=new List<Invoice__c>();
        Branch__c branchrecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
        Account accountReccord = ICRA_TestDataFactory.CreateAccount('Test Account2','Issuer',branchrecord.Id);
        Insert accountReccord;
        
        Opportunity opportunityRecord = ICRA_TestDataFactory.creatOpportunity('Test Opportunnity2', 'Surveillance', accountReccord.Id);
         opportunityRecord.Instrument_type_1__c = 'Non Structured Finance';
        opportunityRecord.Instrument_type_2__c = 'Rating - Bank Loan Rating';
        opportunityRecord.Instrument_type_3__c = 'Bank Loan Rating';
        opportunityRecord.Instrument_type_4__c = 'Bank Loan Rating';
        opportunityRecord.Billing_Start_Date__c = System.today();
        opportunityRecord.Billing_End_Date__c = System.today().addYears(1);
        opportunityRecord.ASF_Final_Amount__c = 0; 
        
        
        insert opportunityRecord;
        Invoice__c invoiceRecord = ICRA_TestDataFactory.createInvoice('Invoice',opportunityRecord.Id,null,null);
        insert invoiceRecord;
        
        Invoice_Line_Item__c invl = ICRA_TestDataFactory.createInvoiceLineItem(invoiceRecord.Id, opportunityRecord.Id);
        
        invlist.add(invoiceRecord);
        if(invlist.size() > 0){
        update invlist;
        }
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new RestMockServerError());
        ICRA_GenerateIRN.InvokeIRN(invlist);
        Test.stopTest();
    }
    
    @isTest
    public static void generateinvoice() {
        
        Branch__c branchrecord = ICRA_TestDataFactory.createBranchRecord('Gurgaon');
        Account accountReccord = ICRA_TestDataFactory.CreateAccount('Test Account3','Issuer',branchrecord.Id);
        Insert accountReccord;
        Opportunity opportunityRecord = ICRA_TestDataFactory.creatOpportunity('Test Opportunnity3', 'Surveillance', accountReccord.Id);
         opportunityRecord.Instrument_type_1__c = 'Non Structured Finance';
        opportunityRecord.Instrument_type_2__c = 'Rating - Bank Loan Rating';
        opportunityRecord.Instrument_type_3__c = 'Bank Loan Rating';
        opportunityRecord.Instrument_type_4__c = 'Bank Loan Rating';
        opportunityRecord.Billing_Start_Date__c = System.today();
        opportunityRecord.Billing_End_Date__c = System.today().addYears(1); 
        opportunityRecord.ASF_Final_Amount__c = 0; 
        insert opportunityRecord;
        Invoice__c invoiceRecord = ICRA_TestDataFactory.createInvoice('Invoice',opportunityRecord.Id,null,null);
        insert invoiceRecord;
        Invoice_Line_Item__c invl = ICRA_TestDataFactory.createInvoiceLineItem(invoiceRecord.Id, opportunityRecord.Id);
        
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new RestMockError());
        ICRA_GenerateIRN.getIRN(invoiceRecord.Id,invoiceRecord.Bill_No__c);
        ICRA_GenerateIRN.updateInvoice(invoiceRecord.IRN_Number__c,invoiceRecord.Id, null, invoiceRecord.Invoice_Status__c);
        Test.stopTest();
    }
}