force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/Manual_Invoice__c.object-meta.xml
<CustomObject>
    <label>Manual Invoice</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Manual Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Manual Invoices (Branch)</relationshipLabel>
    <relationshipName>Manual_Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/recordTypes/ISD.recordType-meta.xml
<RecordType>
    <fullName>ISD</fullName>
    <active>true</active>
    <label>ISD</label>
</RecordType>

force-app/main/default/classes/ICRA_ManualInvoiceISD_Test.cls
@isTest
public with sharing class ICRA_ManualInvoiceISD_Test {
@testsetup 
    public static void isDataSetup(){
     Branch__c branchRecord = ICRA_TestDataFactory.createBranchRecord('Test Branch');
     Manual_Invoice__c manualISD = ICRA_TestDataFactory.createISDrecord('ISD',branchRecord.Id);
    }
    @isTest
    public static void manualISDcontrollerTest(){
        Manual_Invoice__c manualISD = [SELECT Id,Name FROM Manual_Invoice__c LIMIT 1];
        PageReference pageRef = Page.ICRA_ManualInvoice_ISD_pdf;
        ApexPages.currentPage().getParameters().put('id',manualISD.Id);
        ICRA_Controller_ManualInvoice_ISD manualISDpdf = new ICRA_Controller_ManualInvoice_ISD(new ApexPages.StandardController(manualISD));
        manualISDpdf.savePDF();

    } 
    
}