force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Updated_Surveillance_fees_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Updated_Surveillance_fees_Sequence__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Updated Surveillance fees Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Billing_Number__c.field-meta.xml
<CustomField>
    <fullName>Billing_Number__c</fullName>
    <label>Billing Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Status__c</fullName>
    <label>Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Proforma Invoice</fullName>
                <default>true</default>
                <label>Proforma Invoice</label>
            </value>
            <value>
                <fullName>Tax Invoice</fullName>
            </value>
            <value>
                <fullName>QR-IRN-Generated</fullName>
                <label>QR and IRN - Generated</label>
            </value>
            <value>
                <fullName>QR and IRN - Failed</fullName>
            </value>
            <value>
                <fullName>Initiate Tax Invoice</fullName>
            </value>
            <value>
                <fullName>GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Initiate GST Credit Note</fullName>
            </value>
            <value>
                <fullName>Cancel Due to Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Proforma_Invoice_Status__c.field-meta.xml
<CustomField>
    <fullName>Proforma_Invoice_Status__c</fullName>
    <description>To check the approval status of a proforma invoice</description>
    <label>Proforma Invoice Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PI Approved</fullName>
            </value>
            <value>
                <fullName>PI Rejected</fullName>
            </value>
            <value>
                <fullName>PI Pending with Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Skip_PB__c.field-meta.xml
<CustomField>
    <fullName>Skip_PB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to skip the process builder &apos;Genrate_Billing_Number_on_Invoice&apos;</description>
    <label>Skip_PB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Invoice.recordType-meta.xml
<RecordType>
    <fullName>Invoice</fullName>
    <active>true</active>
    <label>Invoice</label>
</RecordType>

force-app/main/default/classes/ICRA_Invoice_Status_Update_Batch.cls
public class ICRA_Invoice_Status_Update_Batch implements Database.Batchable<sObject>, Database.Stateful {
       
    private Date processDate;
    public ICRA_Invoice_Status_Update_Batch(){
        processDate = System.today();
    }

    /* =======       START     ======== */
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            [SELECT Id, Updated_Surveillance_fees_Sequence__c FROM Branch__c]
        );
    }

    /* ==========     EXECUTE      ============= */
    public void execute(Database.BatchableContext bc, List<Branch__c> scope) {
        // Batch size MUST be 1
        Branch__c branch = scope[0];
        System.Debug('Executing ICRA_Invoice_Status_Update_Batch for branch Id: ' + scope[0].Id);
        Date taxInvoiceDate = processDate.addDays((Integer.valueOf(System.Label.Tax_Invoice_Generation)));
        Id surveillance_recordType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Surveillance').getRecordTypeId();
        Savepoint sp = Database.setSavepoint();
        // 🔒 Lock branch row to prevent race conditions
        branch = [SELECT Id, Updated_Surveillance_fees_Sequence__c FROM Branch__c WHERE Id = :branch.Id FOR UPDATE];
        List<Invoice__c> invList = [SELECT Id, Billing_Number__c, Invoice_Status__c, Skip_PB__c, Opportunity_Name__c, CreatedDate FROM Invoice__c
                                    WHERE Opportunity_Name__r.Opp_ICRA_Branch__c = :branch.Id
                                      AND Billing_Number__c = NULL
                                      AND Invoice_Status__c = 'Proforma Invoice'
                                      AND Proforma_Invoice_Status__c!= 'PI Rejected'
                                      AND Proforma_Invoice_Status__c!= 'PI Pending with Finance'
                                      AND Opportunity_Name__r.Billing_Start_Date__c<= :taxInvoiceDate
                                      AND Opportunity_Name__r.Billing_Start_Date__c>= :processDate
                                      AND Opportunity_Name__r.RecordTypeId = :surveillance_recordType Order by createdDate ASC];
        System.debug('Invoices to update: ' + invList.size());
        Integer runningCounter = branch.Updated_Surveillance_fees_Sequence__c == null ? 0 : Integer.valueOf(branch.Updated_Surveillance_fees_Sequence__c);

        List<Invoice__c> invoicesToUpdate = new List<Invoice__c>();
        if (invList.isEmpty()) {
            return;
        }
        for (Invoice__c inv : invList){
            //runningCounter++;
            //inv.Billing_Number__c = runningCounter;
            inv.Invoice_Status__c = 'Initiate Tax Invoice';
            inv.Skip_PB__c = true;
            invoicesToUpdate.add(inv);
        }
        List<Invoice__c> invoicesToUpdateWithCounter = new List<Invoice__c>();
        // Then update invoices
        if (!invoicesToUpdate.isEmpty()) {
        Database.SaveResult[] results = Database.update(invoicesToUpdate, false);
            for (Integer i = 0; i < results.size(); i++) {
                if (!results[i].isSuccess()) {
                    Invoice__c inv = invoicesToUpdate[i];
                    for (Database.Error err : results[i].getErrors()) {
                        ICRA_TransactionLogHandler.addLog('ICRA_Invoice_Status_Update_Batch', invoicesToUpdate[i].Opportunity_Name__c, invoicesToUpdate[i].Id, 'Invoice Status Update Failed: Proforma Invoice to Initiate Tax Invoice', err.getMessage());
                    }
                }else{
                    runningCounter++;
                    invoicesToUpdate[i].Billing_Number__c = runningCounter;
                    invoicesToUpdateWithCounter.add(invoicesToUpdate[i]);
                }
            }
        }

        if(!invoicesToUpdateWithCounter.isEmpty()){
            update invoicesToUpdateWithCounter;
        }
        // Update branch counter 
        if(branch.Updated_Surveillance_fees_Sequence__c != runningCounter){
            branch.Updated_Surveillance_fees_Sequence__c = runningCounter;
        update branch;
        }

        ICRA_TransactionLogHandler.saveLogs();
    }

    /* ===========     FINISH   ========= */
    public void finish(Database.BatchableContext bc) {
        System.debug('Finished ICRA_Invoice_Status_Update_Batch at ' + System.now());
    }
}