force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/Manual_Invoice__c.object-meta.xml
<CustomObject>
    <label>Manual Invoice</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Manual Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Manual Invoices (Branch)</relationshipLabel>
    <relationshipName>Manual_Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/fields/Description_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Service__c</fullName>
    <label>Description of Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ICRA_InterBranch_InvoiceController_Test.cls
@isTest
public class ICRA_InterBranch_InvoiceController_Test {
    @testsetup 
    public static void isDataSetup(){
          ICRA_TestDataFactory.loadCustomeSetting();
        Branch__c branchRecord = ICRA_TestDataFactory.createBranchRecord('Test Branch');
        Branch__c branchRecord2 = ICRA_TestDataFactory.createBranchRecord('Testing Branch');
        Manual_Invoice__c manualInterBranchRecord = ICRA_TestDataFactory.createInterBranch('Inter-Branch Invoice',branchRecord.Id,branchRecord2.Id);
        manualInterBranchRecord.Description_of_Service__c='Test';
        
    }
    @isTest
    public static void ICRA_InterBranch_Controller_Test(){
         Manual_Invoice__c manualInterBranchRecord = [SELECT Id,Name FROM Manual_Invoice__c LIMIT 1];
        PageReference pageRef = Page.ICRA_InterBranch_Invoice;
        ApexPages.currentPage().getParameters().put('id',manualInterBranchRecord.Id);
        ICRA_Interbranch_InvoiceController manualInterBranch = new ICRA_Interbranch_InvoiceController(new ApexPages.StandardController(manualInterBranchRecord));
        manualInterBranch.savePDF();

    }
}