force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/GSTIN__c.field-meta.xml
<CustomField>
    <fullName>GSTIN__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <label>GSTIN No.</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <label>PAN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MPRA_SOW_BillingContact.cls
public class MPRA_SOW_BillingContact {

    public Contact BillingContactDetails {get;set;}
    public Contact oppContact {get;set;}
    public Contact oppContactName {get;set;}
    public Contact oppContactEmailReceipient {get;set;}
    public Branch__c branchGurgaon {get;set;}
    public MPRA_SOW_BillingContact(ApexPages.StandardController controller){
        String OppId = ''+ApexPages.currentPage().getParameters().get('id'); 
        if(OppId != 'null' && OppId != '' && OppId != null ){
          Opportunity opp= [select id, accountid from Opportunity where id=:OppId limit 1 ];
           
          Contact[] Con=[select id,name,MailingStreet,MailingCity,MailingState,MailingPostalCode,MailingCountry,Phone,Designation__c,Billing_Contact__c,Department,Email	 from contact where accountid=:opp.AccountId and Billing_Contact__c	='Yes'  ];
          if(Con.Size()>0)
          {
               BillingContactDetails=Con[0];
          }
          List<OpportunityContactRole> optyConRole= [select Id, Role, ContactId, OpportunityId from opportunityContactRole where OpportunityId=:OppId /*AND Role='MPRA/SOW' LIMIT 1*/]; 
          if(optyConRole.size()>0){
            for(OpportunityContactRole conRole : optyConRole){
              if(conRole.Role=='MPRA/SOW'){
                Contact cont= [Select Id, Salutation, FirstName, LastName, Designation__c, Email,MobilePhone from Contact where Id=:conRole.ContactId LIMIT 1];
                oppContact=Cont;
              }
              if(conRole.Role=='Name on Invoice'){
                Contact contName= [Select Id, Salutation, FirstName, LastName, Designation__c, Email,MobilePhone from Contact where Id=:conRole.ContactId LIMIT 1];
                oppContactName=contName;
              }
              if(conRole.Role=='Email Recipient'){
                Contact contName= [Select Id, Salutation, FirstName, LastName, Designation__c, Email,MobilePhone from Contact where Id=:conRole.ContactId LIMIT 1];
                oppContactEmailReceipient=contName;
              }
            }
          }
          Branch__c branch=[select id, name,Street__c,City__c,Country__c,State__c,Zip_Postal_Code__c,PAN__c,GSTIN__c from Branch__c where name='Gurgaon' LIMIT 1];
          branchGurgaon=branch;
        }
        
    }
}