force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Inter_Branch_Sequence_MI__c.field-meta.xml
<CustomField>
    <fullName>Inter_Branch_Sequence_MI__c</fullName>
    <label>Inter Branch Sequence MI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/Manual_Invoice__c.object-meta.xml
<CustomObject>
    <label>Manual Invoice</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Manual Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manual_Invoice__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Manual Invoices (Branch)</relationshipLabel>
    <relationshipName>Manual_Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/fields/Source_Branch_1__c.field-meta.xml
<CustomField>
    <fullName>Source_Branch_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Manual Invoices (Source Branch)</relationshipLabel>
    <relationshipName>Manual_Invoices2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manual_Invoice__c/recordTypes/Inter_Branch_Invoice.recordType-meta.xml
<RecordType>
    <fullName>Inter_Branch_Invoice</fullName>
    <active>true</active>
    <label>Inter-Branch Invoice</label>
</RecordType>

force-app/main/default/classes/InterBranch_Handler.cls
public class InterBranch_Handler {
    public static void generateBillingNumber(List<Manual_Invoice__c> manualInvoices) {
        Set<Id> branchIds = new Set<Id>();
        for(Manual_Invoice__c invoice : manualInvoices){
            if (invoice.Source_Branch_1__c != null) {
                branchIds.add(invoice.Source_Branch_1__c);           
            }
        }
        if (branchIds.isEmpty()) return;

        Map<Id, Branch__c> branchMap = new Map<Id, Branch__c>([SELECT Id, Inter_Branch_Sequence_MI__c FROM Branch__c WHERE Id IN :branchIds FOR UPDATE]);
        Map<Id, Decimal> tempCounterMap = new Map<Id, Decimal>();

        Set<Id> recordTypeIds = new Set<Id>();
        for (Manual_Invoice__c inv : manualInvoices) {
            if (inv.RecordTypeId != null) {
                recordTypeIds.add(inv.RecordTypeId);
            }
        }
        Map<Id, RecordType> recordTypeMap = new Map<Id, RecordType>([SELECT Id, DeveloperName FROM RecordType WHERE Id IN :recordTypeIds]);

        for (Manual_Invoice__c inv : manualInvoices) {
            String developerName = recordTypeMap.get(inv.RecordTypeId).DeveloperName;
            if (inv.Source_Branch_1__c != null && branchMap.containsKey(inv.Source_Branch_1__c) && developerName =='Inter_Branch_Invoice' && (inv.Billing_Number__c==0 || inv.Billing_Number__C==null)) {
                System.Debug('====RecordType===='+inv.recordType.DeveloperName+'   ====Source_Branch_Seq No====  '+inv.Source_Branch_1__r.Inter_Branch_Sequence_MI__c+ '   ====Billing No No====  '+inv.Billing_Number__c);
                Branch__c branch = branchMap.get(inv.Source_Branch_1__c);
                Decimal currentValue;

                if (!tempCounterMap.containsKey(branch.Id)){
                    currentValue = branch.Inter_Branch_Sequence_MI__c != null ? branch.Inter_Branch_Sequence_MI__c : 0;
                } else {
                    currentValue = tempCounterMap.get(branch.Id);
                }

                currentValue++; 
                inv.Billing_Number__c = currentValue;
                tempCounterMap.put(branch.Id, currentValue);
            }
        }

        for (Id branchId : tempCounterMap.keySet()) {
            branchMap.get(branchId).Inter_Branch_Sequence_MI__c = tempCounterMap.get(branchId);
        }

        update branchMap.values();
    }
}