force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Debtor_Invoice__c/Debtor_Invoice__c.object-meta.xml
<CustomObject>
    <label>Debtor Invoice</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Debtor Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debtor_Invoice__c/fields/Email_Already_Send__c.field-meta.xml
<CustomField>
    <fullName>Email_Already_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Already Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debtor_Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Debtor_Payment__c/Debtor_Payment__c.object-meta.xml
<CustomObject>
    <label>Debtor Payment</label>
    <nameField>
        <displayFormat>DP-{0000}</displayFormat>
        <label>Debtor Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debtor Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Debtor_Payment__c/fields/Debtor_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Debtor_Invoice__c</fullName>
    <label>Debtor Invoice</label>
    <referenceTo>Debtor_Invoice__c</referenceTo>
    <relationshipLabel>Debtor Payments</relationshipLabel>
    <relationshipName>Debtor_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Batch_Debtor_Invoice_3to6Months_Test.cls
@isTest
public class Batch_Debtor_Invoice_3to6Months_Test {
    
    @testSetup
    public static void DebtorInvoice3to6months(){
        Branch__c branchRecord = ICRA_TestDataFactory.createBranchRecord('Gurugram');
        
        Account accountRecord =  ICRA_TestDataFactory.CreateAccount('Testing Account', 'Issuer', branchRecord.Id);
        accountRecord.Last_Debtor_Invoice_Date__c = date.newInstance(2021, 11, 20);
        insert accountRecord;
        
        Contact contactRecord = ICRA_TestDataFactory.createContact('Testing Contact', 'Yes', 'Account Contact', accountRecord.Id); 
        contactRecord.Debtor_Email__c = 'Yes';
        contactRecord.Contact_Debtor_Type__c = '180Days'; 
        insert contactRecord;
        
        Debtor_Invoice__c debtorInvoiceRecord = ICRA_TestDataFactory.createDebtorInvoiceRecord(accountRecord.id,10000);
        debtorInvoiceRecord.Email_Already_Send__c = false;
        debtorInvoiceRecord.Invoice_Date__c = date.newInstance(2021, 11, 20);
        insert debtorInvoiceRecord;
        
        Debtor_Invoice__c debtorInvoiceRecord1 = ICRA_TestDataFactory.createDebtorInvoiceRecord(accountRecord.id,10000);
        debtorInvoiceRecord1.Email_Already_Send__c = false;
        debtorInvoiceRecord1.Invoice_Date__c = date.newInstance(2021, 11, 20);
        insert debtorInvoiceRecord1;
        
        
        Debtor_Payment__c debtorpaymentRcord = ICRA_TestDataFactory.createDebtorPayment(accountRecord.id,debtorInvoiceRecord.id);
        
    }
    @isTest
    public static void runBatch(){
        Test.startTest();
        Database.executeBatch(new Batch_Debtor_Invoice_3to6Months(),20);
        Test.stopTest();
    }
}