force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Account_Classification__c.field-meta.xml
<CustomField>
    <fullName>Account_Classification__c</fullName>
    <description>Defined for the Inter-Branch Manual Invoice record type</description>
    <label>Account Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non-SEZ</fullName>
                <default>true</default>
                <label>Non - SEZ</label>
            </value>
            <value>
                <fullName>SEZ With Tax</fullName>
            </value>
            <value>
                <fullName>SEZ Without Tax</fullName>
            </value>
            <value>
                <fullName>Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/Market_Share__c.object-meta.xml
<CustomObject>
    <label>Market Share</label>
    <nameField>
        <displayFormat>MS-{00000}</displayFormat>
        <label>Market Share</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market Share</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Market_Share__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select Issuer type of Account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Issuer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Market Share</relationshipLabel>
    <relationshipName>Market_Share</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Account__r.Branch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Business_segment__c.field-meta.xml
<CustomField>
    <fullName>Business_segment__c</fullName>
    <defaultValue>(&quot;Rating&quot;)</defaultValue>
    <label>Business segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rating</fullName>
                <default>true</default>
                <label>Rating</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <formula>TEXT(Account__r.Classification__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BD Team Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Customer_Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Fee_Type__c</fullName>
    <formula>TEXT(Account__r.Customer_Fee_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Fee Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Instrument_type_1__c.field-meta.xml
<CustomField>
    <fullName>Instrument_type_1__c</fullName>
    <label>Instrument type 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>GP_Instrument_Type_1</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Instrument_type_2__c.field-meta.xml
<CustomField>
    <fullName>Instrument_type_2__c</fullName>
    <label>Instrument type 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Instrument_type_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>GP_Instrument_Type_2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Instrument_type_3__c.field-meta.xml
<CustomField>
    <fullName>Instrument_type_3__c</fullName>
    <label>Instrument type 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Instrument_type_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>GP_Instrument_Type_3</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Instrument_type_4__c.field-meta.xml
<CustomField>
    <fullName>Instrument_type_4__c</fullName>
    <label>Instrument type 4</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Instrument_type_3__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>GP_Instrument_Type_4</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/LT_Rating__c.field-meta.xml
<CustomField>
    <fullName>LT_Rating__c</fullName>
    <label>LT Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GP_LT_Rating</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Market_Share__c/fields/Mandate_Type__c.field-meta.xml
<CustomField>
    <fullName>Mandate_Type__c</fullName>
    <label>Mandate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>GP_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/Pricing_Structure__c.object-meta.xml
<CustomObject>
    <label>Pricing Module</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Pricing Structure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Module</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Structure__c/fields/BD_Team_Classification__c.field-meta.xml
<CustomField>
    <fullName>BD_Team_Classification__c</fullName>
    <label>Business Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICG</fullName>
            </value>
            <value>
                <fullName>SECG</fullName>
            </value>
            <value>
                <fullName>ECG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <label>Instrument</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rating - Money Market (Non-SF)</fullName>
            </value>
            <value>
                <fullName>Rating - Bank Loan Rating</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Rating - Money Market (SF)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Min_Fee_Rs_Lacs__c.field-meta.xml
<CustomField>
    <fullName>Min_Fee_Rs_Lacs__c</fullName>
    <label>Min Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>NBFC</fullName>
            </value>
            <value>
                <fullName>HFC</fullName>
            </value>
            <value>
                <fullName>MFI</fullName>
            </value>
            <value>
                <fullName>Securitization</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/Target_Yield__c.field-meta.xml
<CustomField>
    <fullName>Target_Yield__c</fullName>
    <label>Target Yield</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/VOD_Max__c.field-meta.xml
<CustomField>
    <fullName>VOD_Max__c</fullName>
    <label>VOD Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Structure__c/fields/VOD_Min__c.field-meta.xml
<CustomField>
    <fullName>VOD_Min__c</fullName>
    <label>VOD Min</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/Sector_Location_Master__c.object-meta.xml
<CustomObject>
    <label>Sector Location Master</label>
    <nameField>
        <displayFormat>SL-{0000}</displayFormat>
        <label>Sector Location Master  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sector Location Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sector_Location_Master__c/fields/Instrument__c.field-meta.xml
<CustomField>
    <fullName>Instrument__c</fullName>
    <label>Instrument</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/fields/Max_Yield__c.field-meta.xml
<CustomField>
    <fullName>Max_Yield__c</fullName>
    <label>Max IRF Yield</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/fields/Min_Yield__c.field-meta.xml
<CustomField>
    <fullName>Min_Yield__c</fullName>
    <label>Min IRF Yield</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/fields/SL_NO__c.field-meta.xml
<CustomField>
    <fullName>SL_NO__c</fullName>
    <label>SL NO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/fields/Target_of_increase__c.field-meta.xml
<CustomField>
    <fullName>Target_of_increase__c</fullName>
    <label>Target % IRF increase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sector_Location_Master__c/fields/Valid_Value__c.field-meta.xml
<CustomField>
    <fullName>Valid_Value__c</fullName>
    <label>Valid Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/GP_Instrument_Type_1.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Structured Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Non Structured Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <masterLabel>Instrument Type 1</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GP_Instrument_Type_2.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Rating - Money Market (SF)</fullName>
    </customValue>
    <customValue>
        <fullName>Rating - Money Market (Non-SF)</fullName>
    </customValue>
    <customValue>
        <fullName>Rating - Bank Loan Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Sector Research</fullName>
    </customValue>
    <customValue>
        <fullName>Customised Research</fullName>
    </customValue>
    <customValue>
        <fullName>Research + CPR</fullName>
    </customValue>
    <customValue>
        <fullName>CPR</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Others-SF</fullName>
    </customValue>
    <masterLabel>Instrument Type 2</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GP_Instrument_Type_3.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annual</fullName>
    </customValue>
    <customValue>
        <fullName>Asset Backed Security</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Loan Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Bonds</fullName>
    </customValue>
    <customValue>
        <fullName>Collateralized Debt Obligation/Collateralized Loan Obligation</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Paper/Certificate of Deposit/Short-term Debt</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Deposits</fullName>
    </customValue>
    <customValue>
        <fullName>Loan Sell-Off</fullName>
    </customValue>
    <customValue>
        <fullName>Long Term Borrowing Programme</fullName>
    </customValue>
    <customValue>
        <fullName>Mortgage Backed Security</fullName>
    </customValue>
    <customValue>
        <fullName>Mutual Fund</fullName>
    </customValue>
    <customValue>
        <fullName>NCD/Debt</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time Royalty</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Security Receipts</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Borrowing Programme</fullName>
    </customValue>
    <customValue>
        <fullName>Various Debt Instruments</fullName>
    </customValue>
    <customValue>
        <fullName>Others-SF</fullName>
    </customValue>
    <customValue>
        <fullName>CP/CD/STD</fullName>
    </customValue>
    <customValue>
        <fullName>Long-term/Short-term borrowing programme</fullName>
    </customValue>
    <customValue>
        <fullName>BLR/CP</fullName>
    </customValue>
    <customValue>
        <fullName>Borrowing programme</fullName>
    </customValue>
    <customValue>
        <fullName>NCD/Debt - Publicly Placed</fullName>
        <isActive>false</isActive>
        <label>NCD/Debt - Publicly Placed</label>
    </customValue>
    <masterLabel>Instrument Type 3</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GP_Instrument_Type_4.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Assignee Payout</fullName>
    </customValue>
    <customValue>
        <fullName>AT1 Bonds</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Loan Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Loan Rating Enhancement</fullName>
    </customValue>
    <customValue>
        <fullName>Bank Loan Rating Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>Bonds</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Deposit</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Paper</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Deposits</fullName>
    </customValue>
    <customValue>
        <fullName>Hybrid Debt</fullName>
    </customValue>
    <customValue>
        <fullName>Infrastructure Expected Loss Ratings</fullName>
    </customValue>
    <customValue>
        <fullName>Issuer Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Long Term Borrowing Programme</fullName>
    </customValue>
    <customValue>
        <fullName>Loss Estimation/Direct Assignment</fullName>
    </customValue>
    <customValue>
        <fullName>Mutual Fund Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Convertible Debenture</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Pass Through Certificates</fullName>
    </customValue>
    <customValue>
        <fullName>PP- Market Linked Debenture</fullName>
    </customValue>
    <customValue>
        <fullName>Preference Shares</fullName>
    </customValue>
    <customValue>
        <fullName>Project Finance Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Resolution Plan - Independent Credit Evaluation (ICE)</fullName>
    </customValue>
    <customValue>
        <fullName>Security Receipts</fullName>
    </customValue>
    <customValue>
        <fullName>Short Term Borrowing Programme</fullName>
    </customValue>
    <customValue>
        <fullName>Structured Finance Rating</fullName>
    </customValue>
    <customValue>
        <fullName>Sub Debt</fullName>
    </customValue>
    <customValue>
        <fullName>Tier II Bonds</fullName>
    </customValue>
    <customValue>
        <fullName>Various Debt Instruments</fullName>
    </customValue>
    <customValue>
        <fullName>Monitoring Activity</fullName>
    </customValue>
    <customValue>
        <fullName>AIF</fullName>
    </customValue>
    <masterLabel>Instrument Type 4</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GP_LT_Rating.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AAA</fullName>
    </customValue>
    <customValue>
        <fullName>AA+</fullName>
    </customValue>
    <customValue>
        <fullName>AA</fullName>
    </customValue>
    <customValue>
        <fullName>AA-</fullName>
    </customValue>
    <customValue>
        <fullName>A+</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>A-</fullName>
    </customValue>
    <customValue>
        <fullName>BBB+</fullName>
    </customValue>
    <customValue>
        <fullName>BBB</fullName>
    </customValue>
    <customValue>
        <fullName>BBB-</fullName>
    </customValue>
    <customValue>
        <fullName>BB+</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BB-</fullName>
    </customValue>
    <customValue>
        <fullName>B+</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>B-</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>AAA (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>AA+ (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>AA (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>AA- (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>A+ (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>A (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>A- (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>BBB+ (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>BBB (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>BBB- (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>BB+ (CE)</fullName>
    </customValue>
    <customValue>
        <fullName>BB (CE)</fullName>
    </customValue>
    <masterLabel>LT Rating</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/GP_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fresh From Fresh</fullName>
    </customValue>
    <customValue>
        <fullName>Fresh From Poached</fullName>
        <label>Fresh From Competition</label>
    </customValue>
    <customValue>
        <fullName>Fresh From Existing</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestFactory.cls
@isTest
public class TestFactory {
  public static Account getAccount(String name, Boolean doInsert){
    Account a = new Account(name = name,Group_Name__c = 'N/A',OFAC_Document_Received__c = true);
    if(doInsert){
      insert a;
    }
    return a;
  }
  public static Contact getContact(Id accountId, String fname, String lname, Boolean doInsert){
    Contact c = new Contact(firstName = fname, lastName = lname, accountId = accountId);
    if(doInsert){
      insert c;
    }
    return c;
  }
  public static void generateAccountWithContacts(Integer numContacts){
    Account a = getAccount('default account ltd', true);
    List<Contact> contacts = new List<Contact>();
    for(Integer i = 0; i < numContacts; i++){
      String contactName = 'contact' + i;
      contacts.add(getContact(a.id, contactName, contactName, false));
    }
    insert contacts;
  }
  public static Opportunity[] generateOppsForAccount(id accountId, Decimal amount, Integer numOpps){
    List<Opportunity> opps = new List<Opportunity>();
    for(Integer i = 0; i < numOpps; i++){
      Opportunity o = new Opportunity();
      o.name = 'Account ' + i;
      o.accountId = accountid;
      o.amount = amount;
      o.closeDate = Date.today().addDays(5);
      o.stageName = 'L1 Meeting';
      opps.add(o);
    }
    return opps;
  }
    public static Branch__c generateBranch(string Name){
        	Branch__c B = new Branch__c(Name = Name);
    	insert B;
    
    return B;
    }
     public static Lead generateLead(string Company,string LastName,string Branch ){
   		Lead l = new Lead(Company = Company,Branch__c=Branch,Classification__c='ICG',LOB__c='Public Finance',Business_Segment__c='Rating',
                      Instrument_1__c='Structured Finance',Instrument_2__c='Rating - Money Market (SF)',
                          Instrument_3__c='Security Receipts',Instrument_4__c='Security Receipts', LastName = LastName);
    	insert l;
    
    return l;
  }
     public static Market_Share__c generateMarketshare(id accountId){
   		Market_Share__c MS = new Market_Share__c(Account__c  = accountId,LT_Rating__c='A+');
    	insert MS;
    
    return MS;
  }
  public static User generateUser(String profileName){
    UserRole userRole = new UserRole(DeveloperName = 'TestingTeam', Name = 'Testing Team');
    insert userRole;
    User u = new User(
      ProfileId = [SELECT Id FROM Profile WHERE Name = :profileName].Id,
      LastName = 'last',
      Email = 'Cpt.Awesome@awesomesauce.com',
      Username = 'Cpt.Awesome@awesomesauce.com',
      CompanyName = 'Testing Co',
      Title = 'Captian',
      Alias = 'alias',
      TimeZoneSidKey = 'America/Los_Angeles',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
        
      UserRoleId = userRole.Id
    );
    insert u;
    return u;
  }
    public static User createTestUser(Id roleId, Id profID, String fName, String lName,string ManagerIds)
    {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
       
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                                lastName = lName,
                                email = uniqueName + '@test' + orgId + '.org',
                                Username = uniqueName + '@test' + orgId + '.org',
                                EmailEncodingKey = 'ISO-8859-1',
                                Alias = uniqueName.substring(18, 23),
                                TimeZoneSidKey = 'America/Los_Angeles',
                                LocaleSidKey = 'en_US',
                                LanguageLocaleKey = 'en_US',
                                ProfileId = profId,
                                UserRoleId = roleId,
                              ManagerId=ManagerIds
                            	 );
        insert tuser;
        return tuser;
    }
    
     public static Sector_Location_Master__c createsectorlocation(string recordtype,Boolean doInsert)
    {  
         Id SectorreRecordTypeId = Schema.SObjectType.Sector_Location_Master__c.getRecordTypeInfosByName().get('Sector Master').getRecordTypeId();
         Id LocationeRecordTypeId = Schema.SObjectType.Sector_Location_Master__c.getRecordTypeInfosByName().get('Location Master').getRecordTypeId();
         Id SFreRecordTypeId = Schema.SObjectType.Sector_Location_Master__c.getRecordTypeInfosByName().get('SF Master').getRecordTypeId();
           
       Sector_Location_Master__c slm=New Sector_Location_Master__c();
        if(recordtype==SectorreRecordTypeId){
            slm.Instrument__c='Rating - Bank Loan Rating';
            slm.Sector__c='Engineering';
            slm.Valid_Value__c='Engineering - Capital Goods';
            slm.RecordTypeId=SectorreRecordTypeId;
        }
         if(recordtype==LocationeRecordTypeId){
            slm.Instrument__c='Rating - Bank Loan Rating';
            slm.Location__c='Mumbai';
            slm.Valid_Value__c='Mumbai';
            slm.RecordTypeId=LocationeRecordTypeId;
        }
         if(recordtype==SFreRecordTypeId){
            slm.SL_NO__c=1.0;
            slm.Min_Yield__c=0.0;
            slm.Max_Yield__c=2.5;
            slm.Target_of_increase__c='15';
            slm.RecordTypeId=SFreRecordTypeId;
        }
        if(doInsert)
        {
            insert slm;
        }
        return slm;            
            
        }
      public static Pricing_Structure__c createPricestructure(string BD_classifaction,Boolean doInsert)
       {  
         Id SectorreRecordTypeId = Schema.SObjectType.Sector_Location_Master__c.getRecordTypeInfosByName().get('Sector Master').getRecordTypeId();
         Id LocationeRecordTypeId = Schema.SObjectType.Sector_Location_Master__c.getRecordTypeInfosByName().get('Location Master').getRecordTypeId();
         Id SFreRecordTypeId = Schema.SObjectType.Sector_Location_Master__c.getRecordTypeInfosByName().get('SF Master').getRecordTypeId();
           
       Pricing_Structure__c prm=New Pricing_Structure__c();
        if(BD_classifaction=='ICG'){
            prm.Instrument__c='Rating - Bank Loan Rating';
            prm.Location__c='Mumbai';
            prm.Sector__c='Engineering';
            prm.BD_Team_Classification__c=BD_classifaction;
            prm.VOD_Min__c=0.0;
            prm.VOD_Max__c=251;
            prm.Target_Yield__c=0.20;
            prm.Min_Fee_Rs_Lacs__c=500000.00;
        }
        if(BD_classifaction=='SECG'){
            prm.Instrument__c='Rating - Bank Loan Rating';
            prm.Location__c='Mumbai';
            prm.Sector__c='Engineering';
            prm.BD_Team_Classification__c=BD_classifaction;
            prm.VOD_Min__c=0.0;
            prm.VOD_Max__c=251;
            prm.Target_Yield__c=2.0;
            prm.Min_Fee_Rs_Lacs__c=35000.00;
        }
        
        if(doInsert)
        {
            insert prm;
        }
        return prm;            
            
        }
      public static Account CreateAccount(String Name, String Recordtype,Boolean doInsert){
        
        Account accountRecord = new Account();
        accountRecord.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(RecordType).getRecordTypeId();
        accountRecord.Name = Name;
        accountRecord.Account_Classification__c = 'Non-SEZ';
        accountRecord.GST_Number__c = 'GST115451a';
        accountRecord.PAN_Number__c = 'RTYUV5554A';
        accountRecord.TAN_Number__c = 'TAN5454141';
           
          if(doInsert){
             insert accountRecord;
          }
        
        return accountRecord;
    }
        public static Opportunity CreateOpportunityNonstructured_FFF(String Name, String Recordtype,String accountID,Boolean doInsert){
        
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.RecordTypeId =Recordtype;
        opportunityRecord.Name = name;
        opportunityRecord.AccountId = accountID;
        opportunityRecord.Customer_Fee_Type__c='Non - Cap';
        opportunityRecord.Business_Segment__c = 'Rating';
        opportunityRecord.Mandate_Type__c = 'Fresh From Fresh';
        opportunityRecord.Type_Tender__c = 'Non - Tender';
        opportunityRecord.StageName ='L1 Meeting';
        opportunityRecord.Conversion_Probability__c = 'High';
        opportunityRecord.Likely_Initial_Rating_Fee__c =1000000;
        opportunityRecord.Instrument_type_1__c ='Non Structured Finance';
        opportunityRecord.Instrument_type_2__c ='Rating - Bank Loan Rating';
        opportunityRecord.Instrument_type_3__c ='Bank Loan Rating';
        opportunityRecord.Instrument_type_4__c ='Bank Loan Rating Fresh';
        opportunityRecord.VoD_in_crore__c =20;
        opportunityRecord.CurrencyIsoCode = 'INR';
        opportunityRecord.Mandate_Received_Date__c =System.today();
        opportunityRecord.GST_Not_Applicable__c = false;
        //opportunityRecord.CloseDate= date.newInstance(2022, 03, 31);
        opportunityRecord.CloseDate = system.today();        
                 
          if(doInsert){
             insert opportunityRecord;
          }
        
        return opportunityRecord;
    }
    
     public static Opportunity CreateOpportunitystructured_FFF(String Name, String Recordtype,String accountID,Boolean doInsert){
        
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.RecordTypeId =Recordtype;
        opportunityRecord.Name = name;
        opportunityRecord.AccountId = accountID;
        opportunityRecord.Customer_Fee_Type__c='Non - Cap';
        opportunityRecord.Business_Segment__c = 'Rating';
        opportunityRecord.Mandate_Type__c = 'Fresh From Fresh';
        opportunityRecord.Type_Tender__c = 'Non - Tender';
        opportunityRecord.StageName ='L1 Meeting';
        opportunityRecord.Conversion_Probability__c = 'High';
        opportunityRecord.Likely_Initial_Rating_Fee__c =1000000;
        opportunityRecord.Instrument_type_1__c ='Structured Finance';
        opportunityRecord.Instrument_type_2__c ='Rating - Money Market (SF)';
        opportunityRecord.Instrument_type_3__c ='Security Receipts';
        opportunityRecord.Instrument_type_4__c ='Pass Through Certificates';
        opportunityRecord.VoD_in_crore__c =20;
        opportunityRecord.CurrencyIsoCode = 'INR';
        opportunityRecord.Mandate_Received_Date__c =System.today();
        opportunityRecord.GST_Not_Applicable__c = false;
        //opportunityRecord.CloseDate= date.newInstance(2022, 03, 31);
        opportunityRecord.CloseDate= system.today();
                 
          if(doInsert){
             insert opportunityRecord;
          }
        
        return opportunityRecord;
    }
   
      public static User createTestUser1(Id profID, String fName, String lName,string ManagerIds)
    {
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User tuser = new User(  firstname = fName,
                              lastName = lName,
                              email = uniqueName + '@test' + orgId + '.org',
                              Username = uniqueName + '@test' + orgId + '.org',
                              EmailEncodingKey = 'ISO-8859-1',
                              Alias = uniqueName.substring(18, 23),
                              TimeZoneSidKey = 'America/Los_Angeles',
                              LocaleSidKey = 'en_US',
                              LanguageLocaleKey = 'en_US',
                              Designation__c='xyz',
                              ProfileId = profId,
                              
                              ManagerId=ManagerIds
                             );
        insert tuser;
        return tuser;
    }
    
}