force-app/main/default/objects/Employee_KRA__c/Employee_KRA__c.object-meta.xml
<CustomObject>
    <label>Employee KRA</label>
    <nameField>
        <displayFormat>KRA-{000000}</displayFormat>
        <label>KRA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee KRA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_KRA__c/fields/Financial_Year__c.field-meta.xml
<CustomField>
    <fullName>Financial_Year__c</fullName>
    <label>Financial Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2021-2022</fullName>
            </value>
            <value>
                <fullName>2022-2023</fullName>
            </value>
            <value>
                <fullName>2023-2024</fullName>
            </value>
            <value>
                <fullName>2024-2025</fullName>
            </value>
            <value>
                <fullName>2025-2026</fullName>
            </value>
            <value>
                <fullName>2026-2027</fullName>
            </value>
            <value>
                <fullName>2027-2028</fullName>
            </value>
            <value>
                <fullName>2028-2029</fullName>
            </value>
            <value>
                <fullName>2029-2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_KRA__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1-April-June</fullName>
            </value>
            <value>
                <fullName>Q2-July-September</fullName>
            </value>
            <value>
                <fullName>Q3-October-December</fullName>
            </value>
            <value>
                <fullName>Q4-January-March</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DuplicateEmployeeKRA_Test.cls
@isTest
public class DuplicateEmployeeKRA_Test {
      static testMethod void positiveDataInsert1()
    {
        Test.startTest();
        Employee_KRA__c EK=new Employee_KRA__c(Status__c='Approved',Financial_Year__c='2022-2023',Quarter__c='Q1-April-June	');
            insert EK;
        
         PageReference pageRef = Page.CallKRABatch;
         Test.setCurrentPage(pageRef);

     pageRef.getParameters().put('Id', String.valueOf(EK.Id));
     ApexPages.StandardController sc = new ApexPages.StandardController(EK);
     CallKRABatch testAccPlan = new CallKRABatch(sc);
        testAccPlan.CalculateKra();
        Test.stopTest();
    }

}